In [ ]:
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "Task 3"
      ],
      "metadata": {
        "id": "rMGwRaw9us9f"
      }
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "id": "qovH03houYEV"
      },
      "outputs": [],
      "source": [
        "import pandas as pd\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.tree import DecisionTreeClassifier\n",
        "from sklearn.metrics import accuracy_score, classification_report, confusion_matrix\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "from sklearn.tree import export_text\n",
        "from sklearn.tree import export_graphviz\n",
        "import graphviz"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data = pd.read_csv(\"bank.csv\")\n",
        "data.head()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 206
        },
        "id": "Ck1iDU3Ju30f",
        "outputId": "d85e2d98-159c-434d-860b-5691a94b240e"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "   age         job  marital  education default  balance housing loan  contact  \\\n",
              "0   59      admin.  married  secondary      no     2343     yes   no  unknown   \n",
              "1   56      admin.  married  secondary      no       45      no   no  unknown   \n",
              "2   41  technician  married  secondary      no     1270     yes   no  unknown   \n",
              "3   55    services  married  secondary      no     2476     yes   no  unknown   \n",
              "4   54      admin.  married   tertiary      no      184      no   no  unknown   \n",
              "\n",
              "   day month  duration  campaign  pdays  previous poutcome deposit  \n",
              "0    5   may      1042         1     -1         0  unknown     yes  \n",
              "1    5   may      1467         1     -1         0  unknown     yes  \n",
              "2    5   may      1389         1     -1         0  unknown     yes  \n",
              "3    5   may       579         1     -1         0  unknown     yes  \n",
              "4    5   may       673         2     -1         0  unknown     yes  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-695558f6-1da0-478e-bca4-21efddcce38f\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>age</th>\n",
              "      <th>job</th>\n",
              "      <th>marital</th>\n",
              "      <th>education</th>\n",
              "      <th>default</th>\n",
              "      <th>balance</th>\n",
              "      <th>housing</th>\n",
              "      <th>loan</th>\n",
              "      <th>contact</th>\n",
              "      <th>day</th>\n",
              "      <th>month</th>\n",
              "      <th>duration</th>\n",
              "      <th>campaign</th>\n",
              "      <th>pdays</th>\n",
              "      <th>previous</th>\n",
              "      <th>poutcome</th>\n",
              "      <th>deposit</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>59</td>\n",
              "      <td>admin.</td>\n",
              "      <td>married</td>\n",
              "      <td>secondary</td>\n",
              "      <td>no</td>\n",
              "      <td>2343</td>\n",
              "      <td>yes</td>\n",
              "      <td>no</td>\n",
              "      <td>unknown</td>\n",
              "      <td>5</td>\n",
              "      <td>may</td>\n",
              "      <td>1042</td>\n",
              "      <td>1</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>unknown</td>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>56</td>\n",
              "      <td>admin.</td>\n",
              "      <td>married</td>\n",
              "      <td>secondary</td>\n",
              "      <td>no</td>\n",
              "      <td>45</td>\n",
              "      <td>no</td>\n",
              "      <td>no</td>\n",
              "      <td>unknown</td>\n",
              "      <td>5</td>\n",
              "      <td>may</td>\n",
              "      <td>1467</td>\n",
              "      <td>1</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>unknown</td>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>41</td>\n",
              "      <td>technician</td>\n",
              "      <td>married</td>\n",
              "      <td>secondary</td>\n",
              "      <td>no</td>\n",
              "      <td>1270</td>\n",
              "      <td>yes</td>\n",
              "      <td>no</td>\n",
              "      <td>unknown</td>\n",
              "      <td>5</td>\n",
              "      <td>may</td>\n",
              "      <td>1389</td>\n",
              "      <td>1</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>unknown</td>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>55</td>\n",
              "      <td>services</td>\n",
              "      <td>married</td>\n",
              "      <td>secondary</td>\n",
              "      <td>no</td>\n",
              "      <td>2476</td>\n",
              "      <td>yes</td>\n",
              "      <td>no</td>\n",
              "      <td>unknown</td>\n",
              "      <td>5</td>\n",
              "      <td>may</td>\n",
              "      <td>579</td>\n",
              "      <td>1</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>unknown</td>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>54</td>\n",
              "      <td>admin.</td>\n",
              "      <td>married</td>\n",
              "      <td>tertiary</td>\n",
              "      <td>no</td>\n",
              "      <td>184</td>\n",
              "      <td>no</td>\n",
              "      <td>no</td>\n",
              "      <td>unknown</td>\n",
              "      <td>5</td>\n",
              "      <td>may</td>\n",
              "      <td>673</td>\n",
              "      <td>2</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>unknown</td>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-695558f6-1da0-478e-bca4-21efddcce38f')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-695558f6-1da0-478e-bca4-21efddcce38f button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-695558f6-1da0-478e-bca4-21efddcce38f');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "<div id=\"df-726853c4-8a5d-4a27-9ea8-b830b4144b95\">\n",
              "  <button class=\"colab-df-quickchart\" onclick=\"quickchart('df-726853c4-8a5d-4a27-9ea8-b830b4144b95')\"\n",
              "            title=\"Suggest charts\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "     width=\"24px\">\n",
              "    <g>\n",
              "        <path d=\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z\"/>\n",
              "    </g>\n",
              "</svg>\n",
              "  </button>\n",
              "\n",
              "<style>\n",
              "  .colab-df-quickchart {\n",
              "      --bg-color: #E8F0FE;\n",
              "      --fill-color: #1967D2;\n",
              "      --hover-bg-color: #E2EBFA;\n",
              "      --hover-fill-color: #174EA6;\n",
              "      --disabled-fill-color: #AAA;\n",
              "      --disabled-bg-color: #DDD;\n",
              "  }\n",
              "\n",
              "  [theme=dark] .colab-df-quickchart {\n",
              "      --bg-color: #3B4455;\n",
              "      --fill-color: #D2E3FC;\n",
              "      --hover-bg-color: #434B5C;\n",
              "      --hover-fill-color: #FFFFFF;\n",
              "      --disabled-bg-color: #3B4455;\n",
              "      --disabled-fill-color: #666;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart {\n",
              "    background-color: var(--bg-color);\n",
              "    border: none;\n",
              "    border-radius: 50%;\n",
              "    cursor: pointer;\n",
              "    display: none;\n",
              "    fill: var(--fill-color);\n",
              "    height: 32px;\n",
              "    padding: 0;\n",
              "    width: 32px;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart:hover {\n",
              "    background-color: var(--hover-bg-color);\n",
              "    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "    fill: var(--button-hover-fill-color);\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart-complete:disabled,\n",
              "  .colab-df-quickchart-complete:disabled:hover {\n",
              "    background-color: var(--disabled-bg-color);\n",
              "    fill: var(--disabled-fill-color);\n",
              "    box-shadow: none;\n",
              "  }\n",
              "\n",
              "  .colab-df-spinner {\n",
              "    border: 2px solid var(--fill-color);\n",
              "    border-color: transparent;\n",
              "    border-bottom-color: var(--fill-color);\n",
              "    animation:\n",
              "      spin 1s steps(1) infinite;\n",
              "  }\n",
              "\n",
              "  @keyframes spin {\n",
              "    0% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "      border-left-color: var(--fill-color);\n",
              "    }\n",
              "    20% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    30% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    40% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    60% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    80% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "    90% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "  }\n",
              "</style>\n",
              "\n",
              "  <script>\n",
              "    async function quickchart(key) {\n",
              "      const quickchartButtonEl =\n",
              "        document.querySelector('#' + key + ' button');\n",
              "      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\n",
              "      quickchartButtonEl.classList.add('colab-df-spinner');\n",
              "      try {\n",
              "        const charts = await google.colab.kernel.invokeFunction(\n",
              "            'suggestCharts', [key], {});\n",
              "      } catch (error) {\n",
              "        console.error('Error during call to suggestCharts:', error);\n",
              "      }\n",
              "      quickchartButtonEl.classList.remove('colab-df-spinner');\n",
              "      quickchartButtonEl.classList.add('colab-df-quickchart-complete');\n",
              "    }\n",
              "    (() => {\n",
              "      let quickchartButtonEl =\n",
              "        document.querySelector('#df-726853c4-8a5d-4a27-9ea8-b830b4144b95 button');\n",
              "      quickchartButtonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "    })();\n",
              "  </script>\n",
              "</div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "data",
              "summary": "{\n  \"name\": \"data\",\n  \"rows\": 11162,\n  \"fields\": [\n    {\n      \"column\": \"age\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 11,\n        \"min\": 18,\n        \"max\": 95,\n        \"num_unique_values\": 76,\n        \"samples\": [\n          54,\n          47,\n          30\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"job\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 12,\n        \"samples\": [\n          \"self-employed\",\n          \"unknown\",\n          \"admin.\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"marital\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"married\",\n          \"single\",\n          \"divorced\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"education\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 4,\n        \"samples\": [\n          \"tertiary\",\n          \"unknown\",\n          \"secondary\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"default\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"yes\",\n          \"no\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"balance\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 3225,\n        \"min\": -6847,\n        \"max\": 81204,\n        \"num_unique_values\": 3805,\n        \"samples\": [\n          3026,\n          1792\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"housing\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"no\",\n          \"yes\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"loan\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"yes\",\n          \"no\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"contact\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"unknown\",\n          \"cellular\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"day\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 8,\n        \"min\": 1,\n        \"max\": 31,\n        \"num_unique_values\": 31,\n        \"samples\": [\n          10,\n          27\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"month\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 12,\n        \"samples\": [\n          \"apr\",\n          \"mar\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"duration\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 347,\n        \"min\": 2,\n        \"max\": 3881,\n        \"num_unique_values\": 1428,\n        \"samples\": [\n          597,\n          346\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"campaign\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 2,\n        \"min\": 1,\n        \"max\": 63,\n        \"num_unique_values\": 36,\n        \"samples\": [\n          31,\n          7\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"pdays\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 108,\n        \"min\": -1,\n        \"max\": 854,\n        \"num_unique_values\": 472,\n        \"samples\": [\n          294,\n          148\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"previous\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 2,\n        \"min\": 0,\n        \"max\": 58,\n        \"num_unique_values\": 34,\n        \"samples\": [\n          30,\n          14\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"poutcome\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 4,\n        \"samples\": [\n          \"other\",\n          \"success\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"deposit\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"no\",\n          \"yes\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 4
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data.tail()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 206
        },
        "id": "u1wXOKMQvF3t",
        "outputId": "e3599c7f-95f9-4a2e-b52b-9f81ab79c1af"
      },
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "       age          job  marital  education default  balance housing loan  \\\n",
              "11157   33  blue-collar   single    primary      no        1     yes   no   \n",
              "11158   39     services  married  secondary      no      733      no   no   \n",
              "11159   32   technician   single  secondary      no       29      no   no   \n",
              "11160   43   technician  married  secondary      no        0      no  yes   \n",
              "11161   34   technician  married  secondary      no        0      no   no   \n",
              "\n",
              "        contact  day month  duration  campaign  pdays  previous poutcome  \\\n",
              "11157  cellular   20   apr       257         1     -1         0  unknown   \n",
              "11158   unknown   16   jun        83         4     -1         0  unknown   \n",
              "11159  cellular   19   aug       156         2     -1         0  unknown   \n",
              "11160  cellular    8   may         9         2    172         5  failure   \n",
              "11161  cellular    9   jul       628         1     -1         0  unknown   \n",
              "\n",
              "      deposit  \n",
              "11157      no  \n",
              "11158      no  \n",
              "11159      no  \n",
              "11160      no  \n",
              "11161      no  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-1f76dc69-7509-441e-acd8-3c80b549b346\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>age</th>\n",
              "      <th>job</th>\n",
              "      <th>marital</th>\n",
              "      <th>education</th>\n",
              "      <th>default</th>\n",
              "      <th>balance</th>\n",
              "      <th>housing</th>\n",
              "      <th>loan</th>\n",
              "      <th>contact</th>\n",
              "      <th>day</th>\n",
              "      <th>month</th>\n",
              "      <th>duration</th>\n",
              "      <th>campaign</th>\n",
              "      <th>pdays</th>\n",
              "      <th>previous</th>\n",
              "      <th>poutcome</th>\n",
              "      <th>deposit</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>11157</th>\n",
              "      <td>33</td>\n",
              "      <td>blue-collar</td>\n",
              "      <td>single</td>\n",
              "      <td>primary</td>\n",
              "      <td>no</td>\n",
              "      <td>1</td>\n",
              "      <td>yes</td>\n",
              "      <td>no</td>\n",
              "      <td>cellular</td>\n",
              "      <td>20</td>\n",
              "      <td>apr</td>\n",
              "      <td>257</td>\n",
              "      <td>1</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>unknown</td>\n",
              "      <td>no</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>11158</th>\n",
              "      <td>39</td>\n",
              "      <td>services</td>\n",
              "      <td>married</td>\n",
              "      <td>secondary</td>\n",
              "      <td>no</td>\n",
              "      <td>733</td>\n",
              "      <td>no</td>\n",
              "      <td>no</td>\n",
              "      <td>unknown</td>\n",
              "      <td>16</td>\n",
              "      <td>jun</td>\n",
              "      <td>83</td>\n",
              "      <td>4</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>unknown</td>\n",
              "      <td>no</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>11159</th>\n",
              "      <td>32</td>\n",
              "      <td>technician</td>\n",
              "      <td>single</td>\n",
              "      <td>secondary</td>\n",
              "      <td>no</td>\n",
              "      <td>29</td>\n",
              "      <td>no</td>\n",
              "      <td>no</td>\n",
              "      <td>cellular</td>\n",
              "      <td>19</td>\n",
              "      <td>aug</td>\n",
              "      <td>156</td>\n",
              "      <td>2</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>unknown</td>\n",
              "      <td>no</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>11160</th>\n",
              "      <td>43</td>\n",
              "      <td>technician</td>\n",
              "      <td>married</td>\n",
              "      <td>secondary</td>\n",
              "      <td>no</td>\n",
              "      <td>0</td>\n",
              "      <td>no</td>\n",
              "      <td>yes</td>\n",
              "      <td>cellular</td>\n",
              "      <td>8</td>\n",
              "      <td>may</td>\n",
              "      <td>9</td>\n",
              "      <td>2</td>\n",
              "      <td>172</td>\n",
              "      <td>5</td>\n",
              "      <td>failure</td>\n",
              "      <td>no</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>11161</th>\n",
              "      <td>34</td>\n",
              "      <td>technician</td>\n",
              "      <td>married</td>\n",
              "      <td>secondary</td>\n",
              "      <td>no</td>\n",
              "      <td>0</td>\n",
              "      <td>no</td>\n",
              "      <td>no</td>\n",
              "      <td>cellular</td>\n",
              "      <td>9</td>\n",
              "      <td>jul</td>\n",
              "      <td>628</td>\n",
              "      <td>1</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>unknown</td>\n",
              "      <td>no</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-1f76dc69-7509-441e-acd8-3c80b549b346')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-1f76dc69-7509-441e-acd8-3c80b549b346 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-1f76dc69-7509-441e-acd8-3c80b549b346');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "<div id=\"df-8798d85a-b567-484a-a36e-50ed00529cdb\">\n",
              "  <button class=\"colab-df-quickchart\" onclick=\"quickchart('df-8798d85a-b567-484a-a36e-50ed00529cdb')\"\n",
              "            title=\"Suggest charts\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "     width=\"24px\">\n",
              "    <g>\n",
              "        <path d=\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z\"/>\n",
              "    </g>\n",
              "</svg>\n",
              "  </button>\n",
              "\n",
              "<style>\n",
              "  .colab-df-quickchart {\n",
              "      --bg-color: #E8F0FE;\n",
              "      --fill-color: #1967D2;\n",
              "      --hover-bg-color: #E2EBFA;\n",
              "      --hover-fill-color: #174EA6;\n",
              "      --disabled-fill-color: #AAA;\n",
              "      --disabled-bg-color: #DDD;\n",
              "  }\n",
              "\n",
              "  [theme=dark] .colab-df-quickchart {\n",
              "      --bg-color: #3B4455;\n",
              "      --fill-color: #D2E3FC;\n",
              "      --hover-bg-color: #434B5C;\n",
              "      --hover-fill-color: #FFFFFF;\n",
              "      --disabled-bg-color: #3B4455;\n",
              "      --disabled-fill-color: #666;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart {\n",
              "    background-color: var(--bg-color);\n",
              "    border: none;\n",
              "    border-radius: 50%;\n",
              "    cursor: pointer;\n",
              "    display: none;\n",
              "    fill: var(--fill-color);\n",
              "    height: 32px;\n",
              "    padding: 0;\n",
              "    width: 32px;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart:hover {\n",
              "    background-color: var(--hover-bg-color);\n",
              "    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "    fill: var(--button-hover-fill-color);\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart-complete:disabled,\n",
              "  .colab-df-quickchart-complete:disabled:hover {\n",
              "    background-color: var(--disabled-bg-color);\n",
              "    fill: var(--disabled-fill-color);\n",
              "    box-shadow: none;\n",
              "  }\n",
              "\n",
              "  .colab-df-spinner {\n",
              "    border: 2px solid var(--fill-color);\n",
              "    border-color: transparent;\n",
              "    border-bottom-color: var(--fill-color);\n",
              "    animation:\n",
              "      spin 1s steps(1) infinite;\n",
              "  }\n",
              "\n",
              "  @keyframes spin {\n",
              "    0% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "      border-left-color: var(--fill-color);\n",
              "    }\n",
              "    20% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    30% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    40% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    60% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    80% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "    90% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "  }\n",
              "</style>\n",
              "\n",
              "  <script>\n",
              "    async function quickchart(key) {\n",
              "      const quickchartButtonEl =\n",
              "        document.querySelector('#' + key + ' button');\n",
              "      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\n",
              "      quickchartButtonEl.classList.add('colab-df-spinner');\n",
              "      try {\n",
              "        const charts = await google.colab.kernel.invokeFunction(\n",
              "            'suggestCharts', [key], {});\n",
              "      } catch (error) {\n",
              "        console.error('Error during call to suggestCharts:', error);\n",
              "      }\n",
              "      quickchartButtonEl.classList.remove('colab-df-spinner');\n",
              "      quickchartButtonEl.classList.add('colab-df-quickchart-complete');\n",
              "    }\n",
              "    (() => {\n",
              "      let quickchartButtonEl =\n",
              "        document.querySelector('#df-8798d85a-b567-484a-a36e-50ed00529cdb button');\n",
              "      quickchartButtonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "    })();\n",
              "  </script>\n",
              "</div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "summary": "{\n  \"name\": \"data\",\n  \"rows\": 5,\n  \"fields\": [\n    {\n      \"column\": \"age\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 4,\n        \"min\": 32,\n        \"max\": 43,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          39,\n          34,\n          32\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"job\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"blue-collar\",\n          \"services\",\n          \"technician\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"marital\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"married\",\n          \"single\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"education\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"secondary\",\n          \"primary\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"default\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 1,\n        \"samples\": [\n          \"no\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"balance\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 324,\n        \"min\": 0,\n        \"max\": 733,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          733\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"housing\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"no\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"loan\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"yes\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"contact\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"unknown\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"day\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 5,\n        \"min\": 8,\n        \"max\": 20,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          16\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"month\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 5,\n        \"samples\": [\n          \"jun\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"duration\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 242,\n        \"min\": 9,\n        \"max\": 628,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          83\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"campaign\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 1,\n        \"max\": 4,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"pdays\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 77,\n        \"min\": -1,\n        \"max\": 172,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          172\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"previous\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 2,\n        \"min\": 0,\n        \"max\": 5,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          5\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"poutcome\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"failure\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"deposit\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 1,\n        \"samples\": [\n          \"no\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 5
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data.columns"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "jNkB1SrvvJey",
        "outputId": "07e41b51-1691-4808-80f2-33fba6cc9f12"
      },
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',\n",
              "       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',\n",
              "       'previous', 'poutcome', 'deposit'],\n",
              "      dtype='object')"
            ]
          },
          "metadata": {},
          "execution_count": 6
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data.shape"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "DNqvAB5ZvTFO",
        "outputId": "4877f873-c14e-4ac8-b3fa-02b4e5bcd202"
      },
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(11162, 17)"
            ]
          },
          "metadata": {},
          "execution_count": 7
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "data.size"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "5PXpEukAvYPL",
        "outputId": "4b3fc860-d074-44af-b74e-592e210da646"
      },
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "189754"
            ]
          },
          "metadata": {},
          "execution_count": 8
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "data.index"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Y62v4mGQvgDg",
        "outputId": "1299f08b-df71-4a3f-9174-2a0cfee8eef6"
      },
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "RangeIndex(start=0, stop=11162, step=1)"
            ]
          },
          "metadata": {},
          "execution_count": 9
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data.describe()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 300
        },
        "id": "GWcFs74Jviit",
        "outputId": "92fc3a4c-9874-4096-ed1c-65ef2a439efc"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "                age       balance           day      duration      campaign  \\\n",
              "count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   \n",
              "mean      41.231948   1528.538524     15.658036    371.993818      2.508421   \n",
              "std       11.913369   3225.413326      8.420740    347.128386      2.722077   \n",
              "min       18.000000  -6847.000000      1.000000      2.000000      1.000000   \n",
              "25%       32.000000    122.000000      8.000000    138.000000      1.000000   \n",
              "50%       39.000000    550.000000     15.000000    255.000000      2.000000   \n",
              "75%       49.000000   1708.000000     22.000000    496.000000      3.000000   \n",
              "max       95.000000  81204.000000     31.000000   3881.000000     63.000000   \n",
              "\n",
              "              pdays      previous  \n",
              "count  11162.000000  11162.000000  \n",
              "mean      51.330407      0.832557  \n",
              "std      108.758282      2.292007  \n",
              "min       -1.000000      0.000000  \n",
              "25%       -1.000000      0.000000  \n",
              "50%       -1.000000      0.000000  \n",
              "75%       20.750000      1.000000  \n",
              "max      854.000000     58.000000  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-5d1dd20e-8d06-4e4d-b221-b36d901c14a4\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>age</th>\n",
              "      <th>balance</th>\n",
              "      <th>day</th>\n",
              "      <th>duration</th>\n",
              "      <th>campaign</th>\n",
              "      <th>pdays</th>\n",
              "      <th>previous</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>count</th>\n",
              "      <td>11162.000000</td>\n",
              "      <td>11162.000000</td>\n",
              "      <td>11162.000000</td>\n",
              "      <td>11162.000000</td>\n",
              "      <td>11162.000000</td>\n",
              "      <td>11162.000000</td>\n",
              "      <td>11162.000000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>mean</th>\n",
              "      <td>41.231948</td>\n",
              "      <td>1528.538524</td>\n",
              "      <td>15.658036</td>\n",
              "      <td>371.993818</td>\n",
              "      <td>2.508421</td>\n",
              "      <td>51.330407</td>\n",
              "      <td>0.832557</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>std</th>\n",
              "      <td>11.913369</td>\n",
              "      <td>3225.413326</td>\n",
              "      <td>8.420740</td>\n",
              "      <td>347.128386</td>\n",
              "      <td>2.722077</td>\n",
              "      <td>108.758282</td>\n",
              "      <td>2.292007</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>min</th>\n",
              "      <td>18.000000</td>\n",
              "      <td>-6847.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>2.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>-1.000000</td>\n",
              "      <td>0.000000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>25%</th>\n",
              "      <td>32.000000</td>\n",
              "      <td>122.000000</td>\n",
              "      <td>8.000000</td>\n",
              "      <td>138.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>-1.000000</td>\n",
              "      <td>0.000000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>50%</th>\n",
              "      <td>39.000000</td>\n",
              "      <td>550.000000</td>\n",
              "      <td>15.000000</td>\n",
              "      <td>255.000000</td>\n",
              "      <td>2.000000</td>\n",
              "      <td>-1.000000</td>\n",
              "      <td>0.000000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>75%</th>\n",
              "      <td>49.000000</td>\n",
              "      <td>1708.000000</td>\n",
              "      <td>22.000000</td>\n",
              "      <td>496.000000</td>\n",
              "      <td>3.000000</td>\n",
              "      <td>20.750000</td>\n",
              "      <td>1.000000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>max</th>\n",
              "      <td>95.000000</td>\n",
              "      <td>81204.000000</td>\n",
              "      <td>31.000000</td>\n",
              "      <td>3881.000000</td>\n",
              "      <td>63.000000</td>\n",
              "      <td>854.000000</td>\n",
              "      <td>58.000000</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-5d1dd20e-8d06-4e4d-b221-b36d901c14a4')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-5d1dd20e-8d06-4e4d-b221-b36d901c14a4 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-5d1dd20e-8d06-4e4d-b221-b36d901c14a4');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "<div id=\"df-7055a79a-4001-4bf1-beb5-cc273d16a28a\">\n",
              "  <button class=\"colab-df-quickchart\" onclick=\"quickchart('df-7055a79a-4001-4bf1-beb5-cc273d16a28a')\"\n",
              "            title=\"Suggest charts\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "     width=\"24px\">\n",
              "    <g>\n",
              "        <path d=\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z\"/>\n",
              "    </g>\n",
              "</svg>\n",
              "  </button>\n",
              "\n",
              "<style>\n",
              "  .colab-df-quickchart {\n",
              "      --bg-color: #E8F0FE;\n",
              "      --fill-color: #1967D2;\n",
              "      --hover-bg-color: #E2EBFA;\n",
              "      --hover-fill-color: #174EA6;\n",
              "      --disabled-fill-color: #AAA;\n",
              "      --disabled-bg-color: #DDD;\n",
              "  }\n",
              "\n",
              "  [theme=dark] .colab-df-quickchart {\n",
              "      --bg-color: #3B4455;\n",
              "      --fill-color: #D2E3FC;\n",
              "      --hover-bg-color: #434B5C;\n",
              "      --hover-fill-color: #FFFFFF;\n",
              "      --disabled-bg-color: #3B4455;\n",
              "      --disabled-fill-color: #666;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart {\n",
              "    background-color: var(--bg-color);\n",
              "    border: none;\n",
              "    border-radius: 50%;\n",
              "    cursor: pointer;\n",
              "    display: none;\n",
              "    fill: var(--fill-color);\n",
              "    height: 32px;\n",
              "    padding: 0;\n",
              "    width: 32px;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart:hover {\n",
              "    background-color: var(--hover-bg-color);\n",
              "    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "    fill: var(--button-hover-fill-color);\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart-complete:disabled,\n",
              "  .colab-df-quickchart-complete:disabled:hover {\n",
              "    background-color: var(--disabled-bg-color);\n",
              "    fill: var(--disabled-fill-color);\n",
              "    box-shadow: none;\n",
              "  }\n",
              "\n",
              "  .colab-df-spinner {\n",
              "    border: 2px solid var(--fill-color);\n",
              "    border-color: transparent;\n",
              "    border-bottom-color: var(--fill-color);\n",
              "    animation:\n",
              "      spin 1s steps(1) infinite;\n",
              "  }\n",
              "\n",
              "  @keyframes spin {\n",
              "    0% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "      border-left-color: var(--fill-color);\n",
              "    }\n",
              "    20% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    30% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    40% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    60% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    80% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "    90% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "  }\n",
              "</style>\n",
              "\n",
              "  <script>\n",
              "    async function quickchart(key) {\n",
              "      const quickchartButtonEl =\n",
              "        document.querySelector('#' + key + ' button');\n",
              "      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\n",
              "      quickchartButtonEl.classList.add('colab-df-spinner');\n",
              "      try {\n",
              "        const charts = await google.colab.kernel.invokeFunction(\n",
              "            'suggestCharts', [key], {});\n",
              "      } catch (error) {\n",
              "        console.error('Error during call to suggestCharts:', error);\n",
              "      }\n",
              "      quickchartButtonEl.classList.remove('colab-df-spinner');\n",
              "      quickchartButtonEl.classList.add('colab-df-quickchart-complete');\n",
              "    }\n",
              "    (() => {\n",
              "      let quickchartButtonEl =\n",
              "        document.querySelector('#df-7055a79a-4001-4bf1-beb5-cc273d16a28a button');\n",
              "      quickchartButtonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "    })();\n",
              "  </script>\n",
              "</div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "summary": "{\n  \"name\": \"data\",\n  \"rows\": 8,\n  \"fields\": [\n    {\n      \"column\": \"age\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 3931.9910823606933,\n        \"min\": 11.913369192215526,\n        \"max\": 11162.0,\n        \"num_unique_values\": 8,\n        \"samples\": [\n          41.231947679627304,\n          39.0,\n          11162.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"balance\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 28556.87170826913,\n        \"min\": -6847.0,\n        \"max\": 81204.0,\n        \"num_unique_values\": 8,\n        \"samples\": [\n          1528.5385235620856,\n          550.0,\n          11162.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"day\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 3941.2684170092043,\n        \"min\": 1.0,\n        \"max\": 11162.0,\n        \"num_unique_values\": 8,\n        \"samples\": [\n          15.658036194230425,\n          15.0,\n          11162.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"duration\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 3883.5837945353724,\n        \"min\": 2.0,\n        \"max\": 11162.0,\n        \"num_unique_values\": 8,\n        \"samples\": [\n          371.99381831213043,\n          255.0,\n          11162.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"campaign\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 3942.6210107711095,\n        \"min\": 1.0,\n        \"max\": 11162.0,\n        \"num_unique_values\": 7,\n        \"samples\": [\n          11162.0,\n          2.508421429851281,\n          3.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"pdays\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 3905.092718695694,\n        \"min\": -1.0,\n        \"max\": 11162.0,\n        \"num_unique_values\": 6,\n        \"samples\": [\n          11162.0,\n          51.33040673714388,\n          854.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"previous\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 3943.27625599434,\n        \"min\": 0.0,\n        \"max\": 11162.0,\n        \"num_unique_values\": 6,\n        \"samples\": [\n          11162.0,\n          0.8325568894463358,\n          58.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 10
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "data.isna().sum()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 617
        },
        "id": "HXsQ-35ovlv5",
        "outputId": "4b793c9b-9921-435e-a388-c6d955df3971"
      },
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "age          0\n",
              "job          0\n",
              "marital      0\n",
              "education    0\n",
              "default      0\n",
              "balance      0\n",
              "housing      0\n",
              "loan         0\n",
              "contact      0\n",
              "day          0\n",
              "month        0\n",
              "duration     0\n",
              "campaign     0\n",
              "pdays        0\n",
              "previous     0\n",
              "poutcome     0\n",
              "deposit      0\n",
              "dtype: int64"
            ],
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>0</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>age</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>job</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>marital</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>education</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>default</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>balance</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>housing</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>loan</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>contact</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>day</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>month</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>duration</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>campaign</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>pdays</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>previous</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>poutcome</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>deposit</th>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div><br><label><b>dtype:</b> int64</label>"
            ]
          },
          "metadata": {},
          "execution_count": 11
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "data.info()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "pokaI7o0vp0K",
        "outputId": "8b1b28d2-82e6-4313-a7c2-6ded687dc847"
      },
      "execution_count": 12,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "<class 'pandas.core.frame.DataFrame'>\n",
            "RangeIndex: 11162 entries, 0 to 11161\n",
            "Data columns (total 17 columns):\n",
            " #   Column     Non-Null Count  Dtype \n",
            "---  ------     --------------  ----- \n",
            " 0   age        11162 non-null  int64 \n",
            " 1   job        11162 non-null  object\n",
            " 2   marital    11162 non-null  object\n",
            " 3   education  11162 non-null  object\n",
            " 4   default    11162 non-null  object\n",
            " 5   balance    11162 non-null  int64 \n",
            " 6   housing    11162 non-null  object\n",
            " 7   loan       11162 non-null  object\n",
            " 8   contact    11162 non-null  object\n",
            " 9   day        11162 non-null  int64 \n",
            " 10  month      11162 non-null  object\n",
            " 11  duration   11162 non-null  int64 \n",
            " 12  campaign   11162 non-null  int64 \n",
            " 13  pdays      11162 non-null  int64 \n",
            " 14  previous   11162 non-null  int64 \n",
            " 15  poutcome   11162 non-null  object\n",
            " 16  deposit    11162 non-null  object\n",
            "dtypes: int64(7), object(10)\n",
            "memory usage: 1.4+ MB\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Define the feature columns and target column\n",
        "features = ['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome']\n",
        "target = 'deposit'"
      ],
      "metadata": {
        "id": "9l0J7P2vvtg3"
      },
      "execution_count": 14,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "data = pd.get_dummies(data, columns=['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome'], drop_first=True)"
      ],
      "metadata": {
        "id": "UGd5Ip1uv2lq"
      },
      "execution_count": 15,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "# Split the data into training and testing sets\n",
        "X = data.drop(target, axis=1)\n",
        "y = data[target]\n",
        "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)\n",
        "X_train"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 461
        },
        "id": "2I4KAhVxv6NP",
        "outputId": "cade0216-9c14-4c7b-b2fd-c781d93d9e3d"
      },
      "execution_count": 16,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "      age  balance  day  duration  campaign  pdays  previous  job_blue-collar  \\\n",
              "7968   57      950    9      1272         1     -1         0            False   \n",
              "1456   34      925   13       709         1     -1         0            False   \n",
              "361    41       75    1       479         9     -1         0             True   \n",
              "812    46     4414   18       504         7     -1         0            False   \n",
              "1092   28     4465   28       769         1     -1         0            False   \n",
              "...   ...      ...  ...       ...       ...    ...       ...              ...   \n",
              "5734   47      761   11        80         2     -1         0            False   \n",
              "5191   28      159   16       449         2     33         4            False   \n",
              "5390   35     1144   20       197        13     -1         0            False   \n",
              "860    51      746   25       372         5     -1         0            False   \n",
              "7270   30        2   23       269         1     -1         0            False   \n",
              "\n",
              "      job_entrepreneur  job_housemaid  ...  month_jul  month_jun  month_mar  \\\n",
              "7968             False          False  ...       True      False      False   \n",
              "1456             False          False  ...      False      False      False   \n",
              "361              False          False  ...       True      False      False   \n",
              "812              False          False  ...      False      False      False   \n",
              "1092             False          False  ...      False      False      False   \n",
              "...                ...            ...  ...        ...        ...        ...   \n",
              "5734             False          False  ...       True      False      False   \n",
              "5191             False          False  ...      False      False      False   \n",
              "5390             False          False  ...      False      False      False   \n",
              "860              False          False  ...      False      False      False   \n",
              "7270             False          False  ...      False      False       True   \n",
              "\n",
              "      month_may  month_nov  month_oct  month_sep  poutcome_other  \\\n",
              "7968      False      False      False      False           False   \n",
              "1456      False      False      False      False           False   \n",
              "361       False      False      False      False           False   \n",
              "812       False      False      False      False           False   \n",
              "1092      False      False      False      False           False   \n",
              "...         ...        ...        ...        ...             ...   \n",
              "5734      False      False      False      False           False   \n",
              "5191      False       True      False      False           False   \n",
              "5390      False      False      False      False           False   \n",
              "860       False      False      False      False           False   \n",
              "7270      False      False      False      False           False   \n",
              "\n",
              "      poutcome_success  poutcome_unknown  \n",
              "7968             False              True  \n",
              "1456             False              True  \n",
              "361              False              True  \n",
              "812              False              True  \n",
              "1092             False              True  \n",
              "...                ...               ...  \n",
              "5734             False              True  \n",
              "5191              True             False  \n",
              "5390             False              True  \n",
              "860              False              True  \n",
              "7270             False              True  \n",
              "\n",
              "[7813 rows x 42 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-5e19dfad-ac75-48f4-9306-d52c02ac5313\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>age</th>\n",
              "      <th>balance</th>\n",
              "      <th>day</th>\n",
              "      <th>duration</th>\n",
              "      <th>campaign</th>\n",
              "      <th>pdays</th>\n",
              "      <th>previous</th>\n",
              "      <th>job_blue-collar</th>\n",
              "      <th>job_entrepreneur</th>\n",
              "      <th>job_housemaid</th>\n",
              "      <th>...</th>\n",
              "      <th>month_jul</th>\n",
              "      <th>month_jun</th>\n",
              "      <th>month_mar</th>\n",
              "      <th>month_may</th>\n",
              "      <th>month_nov</th>\n",
              "      <th>month_oct</th>\n",
              "      <th>month_sep</th>\n",
              "      <th>poutcome_other</th>\n",
              "      <th>poutcome_success</th>\n",
              "      <th>poutcome_unknown</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>7968</th>\n",
              "      <td>57</td>\n",
              "      <td>950</td>\n",
              "      <td>9</td>\n",
              "      <td>1272</td>\n",
              "      <td>1</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1456</th>\n",
              "      <td>34</td>\n",
              "      <td>925</td>\n",
              "      <td>13</td>\n",
              "      <td>709</td>\n",
              "      <td>1</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>361</th>\n",
              "      <td>41</td>\n",
              "      <td>75</td>\n",
              "      <td>1</td>\n",
              "      <td>479</td>\n",
              "      <td>9</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>812</th>\n",
              "      <td>46</td>\n",
              "      <td>4414</td>\n",
              "      <td>18</td>\n",
              "      <td>504</td>\n",
              "      <td>7</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1092</th>\n",
              "      <td>28</td>\n",
              "      <td>4465</td>\n",
              "      <td>28</td>\n",
              "      <td>769</td>\n",
              "      <td>1</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5734</th>\n",
              "      <td>47</td>\n",
              "      <td>761</td>\n",
              "      <td>11</td>\n",
              "      <td>80</td>\n",
              "      <td>2</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5191</th>\n",
              "      <td>28</td>\n",
              "      <td>159</td>\n",
              "      <td>16</td>\n",
              "      <td>449</td>\n",
              "      <td>2</td>\n",
              "      <td>33</td>\n",
              "      <td>4</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5390</th>\n",
              "      <td>35</td>\n",
              "      <td>1144</td>\n",
              "      <td>20</td>\n",
              "      <td>197</td>\n",
              "      <td>13</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>860</th>\n",
              "      <td>51</td>\n",
              "      <td>746</td>\n",
              "      <td>25</td>\n",
              "      <td>372</td>\n",
              "      <td>5</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7270</th>\n",
              "      <td>30</td>\n",
              "      <td>2</td>\n",
              "      <td>23</td>\n",
              "      <td>269</td>\n",
              "      <td>1</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>7813 rows × 42 columns</p>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-5e19dfad-ac75-48f4-9306-d52c02ac5313')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-5e19dfad-ac75-48f4-9306-d52c02ac5313 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-5e19dfad-ac75-48f4-9306-d52c02ac5313');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "<div id=\"df-7bea98ad-1f92-47ff-a354-59399c0b7e10\">\n",
              "  <button class=\"colab-df-quickchart\" onclick=\"quickchart('df-7bea98ad-1f92-47ff-a354-59399c0b7e10')\"\n",
              "            title=\"Suggest charts\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "     width=\"24px\">\n",
              "    <g>\n",
              "        <path d=\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z\"/>\n",
              "    </g>\n",
              "</svg>\n",
              "  </button>\n",
              "\n",
              "<style>\n",
              "  .colab-df-quickchart {\n",
              "      --bg-color: #E8F0FE;\n",
              "      --fill-color: #1967D2;\n",
              "      --hover-bg-color: #E2EBFA;\n",
              "      --hover-fill-color: #174EA6;\n",
              "      --disabled-fill-color: #AAA;\n",
              "      --disabled-bg-color: #DDD;\n",
              "  }\n",
              "\n",
              "  [theme=dark] .colab-df-quickchart {\n",
              "      --bg-color: #3B4455;\n",
              "      --fill-color: #D2E3FC;\n",
              "      --hover-bg-color: #434B5C;\n",
              "      --hover-fill-color: #FFFFFF;\n",
              "      --disabled-bg-color: #3B4455;\n",
              "      --disabled-fill-color: #666;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart {\n",
              "    background-color: var(--bg-color);\n",
              "    border: none;\n",
              "    border-radius: 50%;\n",
              "    cursor: pointer;\n",
              "    display: none;\n",
              "    fill: var(--fill-color);\n",
              "    height: 32px;\n",
              "    padding: 0;\n",
              "    width: 32px;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart:hover {\n",
              "    background-color: var(--hover-bg-color);\n",
              "    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "    fill: var(--button-hover-fill-color);\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart-complete:disabled,\n",
              "  .colab-df-quickchart-complete:disabled:hover {\n",
              "    background-color: var(--disabled-bg-color);\n",
              "    fill: var(--disabled-fill-color);\n",
              "    box-shadow: none;\n",
              "  }\n",
              "\n",
              "  .colab-df-spinner {\n",
              "    border: 2px solid var(--fill-color);\n",
              "    border-color: transparent;\n",
              "    border-bottom-color: var(--fill-color);\n",
              "    animation:\n",
              "      spin 1s steps(1) infinite;\n",
              "  }\n",
              "\n",
              "  @keyframes spin {\n",
              "    0% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "      border-left-color: var(--fill-color);\n",
              "    }\n",
              "    20% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    30% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    40% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    60% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    80% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "    90% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "  }\n",
              "</style>\n",
              "\n",
              "  <script>\n",
              "    async function quickchart(key) {\n",
              "      const quickchartButtonEl =\n",
              "        document.querySelector('#' + key + ' button');\n",
              "      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\n",
              "      quickchartButtonEl.classList.add('colab-df-spinner');\n",
              "      try {\n",
              "        const charts = await google.colab.kernel.invokeFunction(\n",
              "            'suggestCharts', [key], {});\n",
              "      } catch (error) {\n",
              "        console.error('Error during call to suggestCharts:', error);\n",
              "      }\n",
              "      quickchartButtonEl.classList.remove('colab-df-spinner');\n",
              "      quickchartButtonEl.classList.add('colab-df-quickchart-complete');\n",
              "    }\n",
              "    (() => {\n",
              "      let quickchartButtonEl =\n",
              "        document.querySelector('#df-7bea98ad-1f92-47ff-a354-59399c0b7e10 button');\n",
              "      quickchartButtonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "    })();\n",
              "  </script>\n",
              "</div>\n",
              "\n",
              "  <div id=\"id_c3c7f395-6a17-46a1-988f-1f388ff4b5cb\">\n",
              "    <style>\n",
              "      .colab-df-generate {\n",
              "        background-color: #E8F0FE;\n",
              "        border: none;\n",
              "        border-radius: 50%;\n",
              "        cursor: pointer;\n",
              "        display: none;\n",
              "        fill: #1967D2;\n",
              "        height: 32px;\n",
              "        padding: 0 0 0 0;\n",
              "        width: 32px;\n",
              "      }\n",
              "\n",
              "      .colab-df-generate:hover {\n",
              "        background-color: #E2EBFA;\n",
              "        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "        fill: #174EA6;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate {\n",
              "        background-color: #3B4455;\n",
              "        fill: #D2E3FC;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate:hover {\n",
              "        background-color: #434B5C;\n",
              "        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "        fill: #FFFFFF;\n",
              "      }\n",
              "    </style>\n",
              "    <button class=\"colab-df-generate\" onclick=\"generateWithVariable('X_train')\"\n",
              "            title=\"Generate code using this dataframe.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "    <script>\n",
              "      (() => {\n",
              "      const buttonEl =\n",
              "        document.querySelector('#id_c3c7f395-6a17-46a1-988f-1f388ff4b5cb button.colab-df-generate');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      buttonEl.onclick = () => {\n",
              "        google.colab.notebook.generateWithVariable('X_train');\n",
              "      }\n",
              "      })();\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "X_train"
            }
          },
          "metadata": {},
          "execution_count": 16
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "X_train\n",
        "X_test"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 461
        },
        "id": "dFZqrjVYv9RI",
        "outputId": "99826975-505c-4779-c8bd-7dbf631c4833"
      },
      "execution_count": 17,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "       age  balance  day  duration  campaign  pdays  previous  \\\n",
              "5527    65      744    5       182         1     -1         0   \n",
              "4541    38     1627   16      1323         9     -1         0   \n",
              "1964    35     4963   14       456         1    300         1   \n",
              "5007    47     8229    8       784         2     -1         0   \n",
              "8928    35     1473   12        84         3     -1         0   \n",
              "...    ...      ...  ...       ...       ...    ...       ...   \n",
              "1052    30      495   21       641         1     -1         0   \n",
              "10702   44       12   19       126         2     -1         0   \n",
              "10466   44     1945   14       191         1     -1         0   \n",
              "8809    55      505   17        58         1    316         1   \n",
              "99      35        0   20      1205         1     -1         0   \n",
              "\n",
              "       job_blue-collar  job_entrepreneur  job_housemaid  ...  month_jul  \\\n",
              "5527             False             False          False  ...       True   \n",
              "4541              True             False          False  ...      False   \n",
              "1964              True             False          False  ...      False   \n",
              "5007              True             False          False  ...      False   \n",
              "8928             False             False          False  ...      False   \n",
              "...                ...               ...            ...  ...        ...   \n",
              "1052             False             False          False  ...      False   \n",
              "10702            False             False          False  ...      False   \n",
              "10466            False             False          False  ...      False   \n",
              "8809             False             False          False  ...      False   \n",
              "99                True             False          False  ...      False   \n",
              "\n",
              "       month_jun  month_mar  month_may  month_nov  month_oct  month_sep  \\\n",
              "5527       False      False      False      False      False      False   \n",
              "4541        True      False      False      False      False      False   \n",
              "1964       False      False       True      False      False      False   \n",
              "5007       False      False      False      False      False      False   \n",
              "8928       False      False       True      False      False      False   \n",
              "...          ...        ...        ...        ...        ...        ...   \n",
              "1052       False      False      False       True      False      False   \n",
              "10702      False      False      False       True      False      False   \n",
              "10466      False      False       True      False      False      False   \n",
              "8809       False      False      False      False      False      False   \n",
              "99         False      False       True      False      False      False   \n",
              "\n",
              "       poutcome_other  poutcome_success  poutcome_unknown  \n",
              "5527            False             False              True  \n",
              "4541            False             False              True  \n",
              "1964            False             False             False  \n",
              "5007            False             False              True  \n",
              "8928            False             False              True  \n",
              "...               ...               ...               ...  \n",
              "1052            False             False              True  \n",
              "10702           False             False              True  \n",
              "10466           False             False              True  \n",
              "8809             True             False             False  \n",
              "99              False             False              True  \n",
              "\n",
              "[3349 rows x 42 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-da39f06b-c775-40a2-83cc-e2574b8274d6\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>age</th>\n",
              "      <th>balance</th>\n",
              "      <th>day</th>\n",
              "      <th>duration</th>\n",
              "      <th>campaign</th>\n",
              "      <th>pdays</th>\n",
              "      <th>previous</th>\n",
              "      <th>job_blue-collar</th>\n",
              "      <th>job_entrepreneur</th>\n",
              "      <th>job_housemaid</th>\n",
              "      <th>...</th>\n",
              "      <th>month_jul</th>\n",
              "      <th>month_jun</th>\n",
              "      <th>month_mar</th>\n",
              "      <th>month_may</th>\n",
              "      <th>month_nov</th>\n",
              "      <th>month_oct</th>\n",
              "      <th>month_sep</th>\n",
              "      <th>poutcome_other</th>\n",
              "      <th>poutcome_success</th>\n",
              "      <th>poutcome_unknown</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>5527</th>\n",
              "      <td>65</td>\n",
              "      <td>744</td>\n",
              "      <td>5</td>\n",
              "      <td>182</td>\n",
              "      <td>1</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4541</th>\n",
              "      <td>38</td>\n",
              "      <td>1627</td>\n",
              "      <td>16</td>\n",
              "      <td>1323</td>\n",
              "      <td>9</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1964</th>\n",
              "      <td>35</td>\n",
              "      <td>4963</td>\n",
              "      <td>14</td>\n",
              "      <td>456</td>\n",
              "      <td>1</td>\n",
              "      <td>300</td>\n",
              "      <td>1</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5007</th>\n",
              "      <td>47</td>\n",
              "      <td>8229</td>\n",
              "      <td>8</td>\n",
              "      <td>784</td>\n",
              "      <td>2</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8928</th>\n",
              "      <td>35</td>\n",
              "      <td>1473</td>\n",
              "      <td>12</td>\n",
              "      <td>84</td>\n",
              "      <td>3</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1052</th>\n",
              "      <td>30</td>\n",
              "      <td>495</td>\n",
              "      <td>21</td>\n",
              "      <td>641</td>\n",
              "      <td>1</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>10702</th>\n",
              "      <td>44</td>\n",
              "      <td>12</td>\n",
              "      <td>19</td>\n",
              "      <td>126</td>\n",
              "      <td>2</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>10466</th>\n",
              "      <td>44</td>\n",
              "      <td>1945</td>\n",
              "      <td>14</td>\n",
              "      <td>191</td>\n",
              "      <td>1</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8809</th>\n",
              "      <td>55</td>\n",
              "      <td>505</td>\n",
              "      <td>17</td>\n",
              "      <td>58</td>\n",
              "      <td>1</td>\n",
              "      <td>316</td>\n",
              "      <td>1</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>99</th>\n",
              "      <td>35</td>\n",
              "      <td>0</td>\n",
              "      <td>20</td>\n",
              "      <td>1205</td>\n",
              "      <td>1</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>True</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>3349 rows × 42 columns</p>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-da39f06b-c775-40a2-83cc-e2574b8274d6')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-da39f06b-c775-40a2-83cc-e2574b8274d6 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-da39f06b-c775-40a2-83cc-e2574b8274d6');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "<div id=\"df-ac917198-a5a5-4f85-bf37-2a17bb1d5087\">\n",
              "  <button class=\"colab-df-quickchart\" onclick=\"quickchart('df-ac917198-a5a5-4f85-bf37-2a17bb1d5087')\"\n",
              "            title=\"Suggest charts\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "     width=\"24px\">\n",
              "    <g>\n",
              "        <path d=\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z\"/>\n",
              "    </g>\n",
              "</svg>\n",
              "  </button>\n",
              "\n",
              "<style>\n",
              "  .colab-df-quickchart {\n",
              "      --bg-color: #E8F0FE;\n",
              "      --fill-color: #1967D2;\n",
              "      --hover-bg-color: #E2EBFA;\n",
              "      --hover-fill-color: #174EA6;\n",
              "      --disabled-fill-color: #AAA;\n",
              "      --disabled-bg-color: #DDD;\n",
              "  }\n",
              "\n",
              "  [theme=dark] .colab-df-quickchart {\n",
              "      --bg-color: #3B4455;\n",
              "      --fill-color: #D2E3FC;\n",
              "      --hover-bg-color: #434B5C;\n",
              "      --hover-fill-color: #FFFFFF;\n",
              "      --disabled-bg-color: #3B4455;\n",
              "      --disabled-fill-color: #666;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart {\n",
              "    background-color: var(--bg-color);\n",
              "    border: none;\n",
              "    border-radius: 50%;\n",
              "    cursor: pointer;\n",
              "    display: none;\n",
              "    fill: var(--fill-color);\n",
              "    height: 32px;\n",
              "    padding: 0;\n",
              "    width: 32px;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart:hover {\n",
              "    background-color: var(--hover-bg-color);\n",
              "    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "    fill: var(--button-hover-fill-color);\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart-complete:disabled,\n",
              "  .colab-df-quickchart-complete:disabled:hover {\n",
              "    background-color: var(--disabled-bg-color);\n",
              "    fill: var(--disabled-fill-color);\n",
              "    box-shadow: none;\n",
              "  }\n",
              "\n",
              "  .colab-df-spinner {\n",
              "    border: 2px solid var(--fill-color);\n",
              "    border-color: transparent;\n",
              "    border-bottom-color: var(--fill-color);\n",
              "    animation:\n",
              "      spin 1s steps(1) infinite;\n",
              "  }\n",
              "\n",
              "  @keyframes spin {\n",
              "    0% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "      border-left-color: var(--fill-color);\n",
              "    }\n",
              "    20% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    30% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    40% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    60% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    80% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "    90% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "  }\n",
              "</style>\n",
              "\n",
              "  <script>\n",
              "    async function quickchart(key) {\n",
              "      const quickchartButtonEl =\n",
              "        document.querySelector('#' + key + ' button');\n",
              "      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\n",
              "      quickchartButtonEl.classList.add('colab-df-spinner');\n",
              "      try {\n",
              "        const charts = await google.colab.kernel.invokeFunction(\n",
              "            'suggestCharts', [key], {});\n",
              "      } catch (error) {\n",
              "        console.error('Error during call to suggestCharts:', error);\n",
              "      }\n",
              "      quickchartButtonEl.classList.remove('colab-df-spinner');\n",
              "      quickchartButtonEl.classList.add('colab-df-quickchart-complete');\n",
              "    }\n",
              "    (() => {\n",
              "      let quickchartButtonEl =\n",
              "        document.querySelector('#df-ac917198-a5a5-4f85-bf37-2a17bb1d5087 button');\n",
              "      quickchartButtonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "    })();\n",
              "  </script>\n",
              "</div>\n",
              "\n",
              "  <div id=\"id_fc774509-fe1e-43df-a763-6b15a1916d4f\">\n",
              "    <style>\n",
              "      .colab-df-generate {\n",
              "        background-color: #E8F0FE;\n",
              "        border: none;\n",
              "        border-radius: 50%;\n",
              "        cursor: pointer;\n",
              "        display: none;\n",
              "        fill: #1967D2;\n",
              "        height: 32px;\n",
              "        padding: 0 0 0 0;\n",
              "        width: 32px;\n",
              "      }\n",
              "\n",
              "      .colab-df-generate:hover {\n",
              "        background-color: #E2EBFA;\n",
              "        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "        fill: #174EA6;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate {\n",
              "        background-color: #3B4455;\n",
              "        fill: #D2E3FC;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate:hover {\n",
              "        background-color: #434B5C;\n",
              "        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "        fill: #FFFFFF;\n",
              "      }\n",
              "    </style>\n",
              "    <button class=\"colab-df-generate\" onclick=\"generateWithVariable('X_test')\"\n",
              "            title=\"Generate code using this dataframe.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "    <script>\n",
              "      (() => {\n",
              "      const buttonEl =\n",
              "        document.querySelector('#id_fc774509-fe1e-43df-a763-6b15a1916d4f button.colab-df-generate');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      buttonEl.onclick = () => {\n",
              "        google.colab.notebook.generateWithVariable('X_test');\n",
              "      }\n",
              "      })();\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "X_test"
            }
          },
          "metadata": {},
          "execution_count": 17
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "y_train"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 458
        },
        "id": "-FSxutprwAh0",
        "outputId": "7a743b1e-78fd-4809-ae3f-b8886098b33c"
      },
      "execution_count": 18,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "7968     no\n",
              "1456    yes\n",
              "361     yes\n",
              "812     yes\n",
              "1092    yes\n",
              "       ... \n",
              "5734     no\n",
              "5191    yes\n",
              "5390     no\n",
              "860     yes\n",
              "7270     no\n",
              "Name: deposit, Length: 7813, dtype: object"
            ],
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>deposit</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>7968</th>\n",
              "      <td>no</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1456</th>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>361</th>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>812</th>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1092</th>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5734</th>\n",
              "      <td>no</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5191</th>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5390</th>\n",
              "      <td>no</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>860</th>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7270</th>\n",
              "      <td>no</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>7813 rows × 1 columns</p>\n",
              "</div><br><label><b>dtype:</b> object</label>"
            ]
          },
          "metadata": {},
          "execution_count": 18
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "y_test"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 458
        },
        "id": "Zoxrm92mwDFb",
        "outputId": "d514f91a-3c50-4289-9570-743e48cd002e"
      },
      "execution_count": 19,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "5527      no\n",
              "4541     yes\n",
              "1964     yes\n",
              "5007     yes\n",
              "8928      no\n",
              "        ... \n",
              "1052     yes\n",
              "10702     no\n",
              "10466     no\n",
              "8809      no\n",
              "99       yes\n",
              "Name: deposit, Length: 3349, dtype: object"
            ],
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>deposit</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>5527</th>\n",
              "      <td>no</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4541</th>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1964</th>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5007</th>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8928</th>\n",
              "      <td>no</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1052</th>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>10702</th>\n",
              "      <td>no</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>10466</th>\n",
              "      <td>no</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8809</th>\n",
              "      <td>no</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>99</th>\n",
              "      <td>yes</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>3349 rows × 1 columns</p>\n",
              "</div><br><label><b>dtype:</b> object</label>"
            ]
          },
          "metadata": {},
          "execution_count": 19
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Create a Decision Tree Classifier\n",
        "clf = DecisionTreeClassifier(random_state=42)"
      ],
      "metadata": {
        "id": "fJxuhQpQwF7U"
      },
      "execution_count": 20,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "clf.fit(X_train, y_train)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 74
        },
        "id": "GT5CLLNmwIw9",
        "outputId": "af888015-ad51-462d-d124-04300037a193"
      },
      "execution_count": 21,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "DecisionTreeClassifier(random_state=42)"
            ],
            "text/html": [
              "<style>#sk-container-id-1 {color: black;}#sk-container-id-1 pre{padding: 0;}#sk-container-id-1 div.sk-toggleable {background-color: white;}#sk-container-id-1 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-1 label.sk-toggleable__label-arrow:before {content: \"▸\";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-1 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-1 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-1 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: \"▾\";}#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-1 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-1 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-1 div.sk-parallel-item::after {content: \"\";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-serial::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-1 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-1 div.sk-item {position: relative;z-index: 1;}#sk-container-id-1 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-1 div.sk-item::before, #sk-container-id-1 div.sk-parallel-item::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-1 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-1 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-1 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-1 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-1 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-1 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-1 div.sk-label-container {text-align: center;}#sk-container-id-1 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-1 div.sk-text-repr-fallback {display: none;}</style><div id=\"sk-container-id-1\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>DecisionTreeClassifier(random_state=42)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-1\" type=\"checkbox\" checked><label for=\"sk-estimator-id-1\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">DecisionTreeClassifier</label><div class=\"sk-toggleable__content\"><pre>DecisionTreeClassifier(random_state=42)</pre></div></div></div></div></div>"
            ]
          },
          "metadata": {},
          "execution_count": 21
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Make Predictions\n",
        "y_pred = clf.predict(X_test)"
      ],
      "metadata": {
        "id": "nHek75B1wM7Z"
      },
      "execution_count": 22,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Evaluate the model\n",
        "accuracy = accuracy_score(y_test, y_pred)\n",
        "print(\"Accuracy:\", accuracy)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "36NcVxAYwP-Z",
        "outputId": "6bd24c48-e682-44e2-fde7-62f356445219"
      },
      "execution_count": 23,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Accuracy: 0.78501045088086\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "conf_matrix = confusion_matrix(y_test, y_pred)\n",
        "print(\"Confusion Matrix:\\n\", conf_matrix)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "kMUdQNywwSqN",
        "outputId": "3a8f8ffe-bb37-48c0-e342-0f032f259260"
      },
      "execution_count": 24,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Confusion Matrix:\n",
            " [[1398  344]\n",
            " [ 376 1231]]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "class_report = classification_report(y_test, y_pred)\n",
        "print(\"Classification Report:\\n\", class_report)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "YOekm-VDwVXA",
        "outputId": "85667d4d-64c3-4a44-afdd-89e7aa31404b"
      },
      "execution_count": 25,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Classification Report:\n",
            "               precision    recall  f1-score   support\n",
            "\n",
            "          no       0.79      0.80      0.80      1742\n",
            "         yes       0.78      0.77      0.77      1607\n",
            "\n",
            "    accuracy                           0.79      3349\n",
            "   macro avg       0.78      0.78      0.78      3349\n",
            "weighted avg       0.78      0.79      0.78      3349\n",
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "confusion = confusion_matrix(y_test, y_pred)\n",
        "plt.figure(figsize=(8, 6))\n",
        "sns.heatmap(confusion, annot=True, fmt=\"d\", cmap=\"Oranges\")\n",
        "plt.xlabel('Predicted')\n",
        "plt.ylabel('Actual')\n",
        "plt.title('Confusion Matrix')\n",
        "plt.show()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 564
        },
        "id": "tVssRmEgwX0A",
        "outputId": "17a149d7-6620-4bc2-d3dd-1d66aa528051"
      },
      "execution_count": 26,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 800x600 with 2 Axes>"
            ],
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAApIAAAIjCAYAAACwHvu2AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/bCgiHAAAACXBIWXMAAA9hAAAPYQGoP6dpAABCUklEQVR4nO3dfXzN9f/H8ec5YzNjm2FXfZm5yEX5uiyNXGW5VqIk+9ZcpeQyF6GioawUaREpIVG64isVibTUsLBIkqtQbMPMbJjZzu8PP+fbadT2bscZ53G/3c7t5rw/78/n8/68b196fZ/vz+dzLDabzSYAAACgkKyuHgAAAACuTRSSAAAAMEIhCQAAACMUkgAAADBCIQkAAAAjFJIAAAAwQiEJAAAAIxSSAAAAMEIhCQAAACMUkgD+0p49e9S2bVv5+fnJYrFo+fLlRXr8X3/9VRaLRQsWLCjS417LWrVqpVatWrl6GADwtygkgWvAvn379Mgjj6hq1aoqVaqUfH191axZM73yyis6e/asU88dHR2tHTt26LnnntOiRYvUuHFjp57vaurdu7csFot8fX0vO4979uyRxWKRxWLRSy+9VOjjHzlyRDExMUpKSiqC0QJA8VPC1QMA8Nc+/fRT3XffffLy8tJDDz2km2++WefPn9eGDRs0evRo7dy5U3PnznXKuc+ePauEhAQ99dRTGjx4sFPOERYWprNnz6pkyZJOOf7fKVGihM6cOaNPPvlEPXr0cNi2ePFilSpVSufOnTM69pEjRzRx4kRVqVJF9evXL/B+X3zxhdH5AOBqo5AEirEDBw6oZ8+eCgsL07p16xQSEmLfNmjQIO3du1effvqp085/7NgxSZK/v7/TzmGxWFSqVCmnHf/veHl5qVmzZnr33XfzFZJLlixRp06d9NFHH12VsZw5c0alS5eWp6fnVTkfAPxTLG0DxdjUqVOVmZmpefPmORSRl1SvXl3Dhg2zf79w4YImT56satWqycvLS1WqVNGTTz6p7Oxsh/2qVKmizp07a8OGDbr11ltVqlQpVa1aVW+//ba9T0xMjMLCwiRJo0ePlsViUZUqVSRdXBK+9Oc/iomJkcVicWhbs2aNbr/9dvn7+6tMmTKqWbOmnnzySfv2K90juW7dOjVv3lw+Pj7y9/fX3XffrV27dl32fHv37lXv3r3l7+8vPz8/9enTR2fOnLnyxP5Jr1699Pnnnys9Pd3elpiYqD179qhXr175+qelpWnUqFGqW7euypQpI19fX3Xo0EE//PCDvc/69et1yy23SJL69OljXyK/dJ2tWrXSzTffrC1btqhFixYqXbq0fV7+fI9kdHS0SpUqle/627Vrp3LlyunIkSMFvlYAKEoUkkAx9sknn6hq1apq2rRpgfr3799fEyZMUMOGDfXyyy+rZcuWio2NVc+ePfP13bt3r+69917deeedmjZtmsqVK6fevXtr586dkqRu3brp5ZdfliQ98MADWrRokWbMmFGo8e/cuVOdO3dWdna2Jk2apGnTpumuu+7St99++5f7ffnll2rXrp1SU1MVExOjESNG6LvvvlOzZs3066+/5uvfo0cPnT59WrGxserRo4cWLFigiRMnFnic3bp1k8Vi0ccff2xvW7JkiWrVqqWGDRvm679//34tX75cnTt31vTp0zV69Gjt2LFDLVu2tBd1tWvX1qRJkyRJAwYM0KJFi7Ro0SK1aNHCfpwTJ06oQ4cOql+/vmbMmKHWrVtfdnyvvPKKKlasqOjoaOXm5kqSXn/9dX3xxRd69dVXFRoaWuBrBYAiZQNQLJ06dcomyXb33XcXqH9SUpJNkq1///4O7aNGjbJJsq1bt87eFhYWZpNki4+Pt7elpqbavLy8bCNHjrS3HThwwCbJ9uKLLzocMzo62hYWFpZvDM8884ztj/+svPzyyzZJtmPHjl1x3JfOMX/+fHtb/fr1bYGBgbYTJ07Y23744Qeb1Wq1PfTQQ/nO17dvX4dj3nPPPbby5ctf8Zx/vA4fHx+bzWaz3XvvvbY2bdrYbDabLTc31xYcHGybOHHiZefg3Llzttzc3HzX4eXlZZs0aZK9LTExMd+1XdKyZUubJNucOXMuu61ly5YObatXr7ZJsj377LO2/fv328qUKWPr2rXr314jADgTiSRQTGVkZEiSypYtW6D+n332mSRpxIgRDu0jR46UpHz3UtapU0fNmze3f69YsaJq1qyp/fv3G4/5zy7dW/nf//5XeXl5Bdrn6NGjSkpKUu/evRUQEGBv//e//60777zTfp1/9Oijjzp8b968uU6cOGGfw4Lo1auX1q9fr+TkZK1bt07JycmXXdaWLt5XabVe/OczNzdXJ06csC/bb926tcDn9PLyUp8+fQrUt23btnrkkUc0adIkdevWTaVKldLrr79e4HMBgDNQSALFlK+vryTp9OnTBep/8OBBWa1WVa9e3aE9ODhY/v7+OnjwoEN75cqV8x2jXLlyOnnypOGI87v//vvVrFkz9e/fX0FBQerZs6fef//9vywqL42zZs2a+bbVrl1bx48fV1ZWlkP7n6+lXLlyklSoa+nYsaPKli2rpUuXavHixbrlllvyzeUleXl5evnll1WjRg15eXmpQoUKqlixorZv365Tp04V+Jw33HBDoR6seemllxQQEKCkpCTFxcUpMDCwwPsCgDNQSALFlK+vr0JDQ/Xjjz8War8/P+xyJR4eHpdtt9lsxue4dP/eJd7e3oqPj9eXX36pBx98UNu3b9f999+vO++8M1/ff+KfXMslXl5e6tatmxYuXKhly5ZdMY2UpClTpmjEiBFq0aKF3nnnHa1evVpr1qzRTTfdVODkVbo4P4Wxbds2paamSpJ27NhRqH0BwBkoJIFirHPnztq3b58SEhL+tm9YWJjy8vK0Z88eh/aUlBSlp6fbn8AuCuXKlXN4wvmSP6eekmS1WtWmTRtNnz5dP/30k5577jmtW7dOX3311WWPfWmcu3fvzrft559/VoUKFeTj4/PPLuAKevXqpW3btun06dOXfUDpkg8//FCtW7fWvHnz1LNnT7Vt21aRkZH55qSgRX1BZGVlqU+fPqpTp44GDBigqVOnKjExsciODwAmKCSBYuyJJ56Qj4+P+vfvr5SUlHzb9+3bp1deeUXSxaVZSfmerJ4+fbokqVOnTkU2rmrVqunUqVPavn27ve3o0aNatmyZQ7+0tLR8+156MfefX0l0SUhIiOrXr6+FCxc6FGY//vijvvjiC/t1OkPr1q01efJkzZw5U8HBwVfs5+HhkS/t/OCDD/T77787tF0qeC9XdBfWmDFjdOjQIS1cuFDTp09XlSpVFB0dfcV5BICrgReSA8VYtWrVtGTJEt1///2qXbu2wy/bfPfdd/rggw/Uu3dvSVK9evUUHR2tuXPnKj09XS1bttTmzZu1cOFCde3a9YqvljHRs2dPjRkzRvfcc4+GDh2qM2fOaPbs2brxxhsdHjaZNGmS4uPj1alTJ4WFhSk1NVWvvfaa/vWvf+n222+/4vFffPFFdejQQREREerXr5/Onj2rV199VX5+foqJiSmy6/gzq9Wqp59++m/7de7cWZMmTVKfPn3UtGlT7dixQ4sXL1bVqlUd+lWrVk3+/v6aM2eOypYtKx8fHzVp0kTh4eGFGte6dev02muv6ZlnnrG/jmj+/Plq1aqVxo8fr6lTpxbqeABQVEgkgWLurrvu0vbt23Xvvffqv//9rwYNGqSxY8fq119/1bRp0xQXF2fv++abb2rixIlKTEzU8OHDtW7dOo0bN07vvfdekY6pfPnyWrZsmUqXLq0nnnhCCxcuVGxsrLp06ZJv7JUrV9Zbb72lQYMGadasWWrRooXWrVsnPz+/Kx4/MjJSq1atUvny5TVhwgS99NJLuu222/Ttt98WughzhieffFIjR47U6tWrNWzYMG3dulWffvqpKlWq5NCvZMmSWrhwoTw8PPToo4/qgQce0Ndff12oc50+fVp9+/ZVgwYN9NRTT9nbmzdvrmHDhmnatGnauHFjkVwXABSWxVaYu9EBAACA/0ciCQAAACMUkgAAADBCIQkAAAAjFJIAAAAwQiEJAAAAIxSSAAAAMEIhCQAAACPX5S/bxNQq6eohAHCSmK1HXT0EAM5SuoLLTu3M2iHm5xynHdvVSCQBAABg5LpMJAEAAArD4uoBXKMoJAEAgNuzUEkaYWkbAAAARkgkAQCA2yNZM8O8AQAAwAiJJAAAcHvcI2mGRBIAAABGSCQBAIDbI5A0QyIJAAAAIySSAADA7XGPpBkKSQAA4PZYojXDvAEAAMAIiSQAAHB7LG2bIZEEAACAERJJAADg9ggkzZBIAgAAwAiJJAAAcHvcI2mGRBIAAABGSCQBAIDbI5A0QyEJAADcnpVK0ghL2wAAADBCIgkAANwegaQZEkkAAAAYIZEEAABuj9f/mCGRBAAAgBESSQAA4PYIJM2QSAIAAMAIiSQAAHB7VovN1UO4JlFIAgAAt8fSthmWtgEAAGCERBIAALg9EkkzJJIAAAAwQiIJAADcHi8kN0MiCQAAACMkkgAAwO0RSJohkQQAAIAREkkAAOD2rESSRigkAQCA26OONMPSNgAAAIyQSAIAALfH63/MkEgCAADACIkkAABwewSSZkgkAQAAYIREEgAAuD1e/2OGRBIAAABGSCQBAIDbI5A0QyEJAADcHq//McPSNgAAAIyQSAIAALdHIGmGRBIAAABGSCQBAIDb4x5JMySSAAAAMEIiCQAA3B7JmhnmDQAAAEZIJAEAgNvjHkkzFJIAAMDtUUeaYWkbAAAARkgkAQCA27MSSRohkQQAAIAREkkAAOD2CCTNkEgCAADACIkkAABwe9wjaYZEEgAAAEZIJAEAgNsjWTNDIQkAANwev2xjhgIcAAAARkgkAQCA2yNZM8O8AQAAwAiJJAAAcHvcI2mGRBIAAABGSCQBAIDbs1psrh7CNYlEEgAAAEZIJAEAgNsjWTPDvAEAAMAIiSQAAHB7PLVthkISAAC4PZZozTBvAAAAMEIiCQAA3B5L22ZIJAEAAGCERBIAALg9kjUzzBsAAACMUEgCAAC3Z7U471NY8fHx6tKli0JDQ2WxWLR8+XL7tpycHI0ZM0Z169aVj4+PQkND9dBDD+nIkSMOx0hLS1NUVJR8fX3l7++vfv36KTMz06HP9u3b1bx5c5UqVUqVKlXS1KlTCz9vhb88AAAAOEtWVpbq1aunWbNm5dt25swZbd26VePHj9fWrVv18ccfa/fu3brrrrsc+kVFRWnnzp1as2aNVq5cqfj4eA0YMMC+PSMjQ23btlVYWJi2bNmiF198UTExMZo7d26hxmqx2WzX3a+Ux9Qq6eohAHCSmK1HXT0EAM5SuoLLTv1VKw+nHbv1+lzjfS0Wi5YtW6auXbtesU9iYqJuvfVWHTx4UJUrV9auXbtUp04dJSYmqnHjxpKkVatWqWPHjvrtt98UGhqq2bNn66mnnlJycrI8PT0lSWPHjtXy5cv1888/F3h8JJIAAMDtWZ34yc7OVkZGhsMnOzu7yMZ+6tQpWSwW+fv7S5ISEhLk7+9vLyIlKTIyUlarVZs2bbL3adGihb2IlKR27dpp9+7dOnnyZIHPTSEJAADgRLGxsfLz83P4xMbGFsmxz507pzFjxuiBBx6Qr6+vJCk5OVmBgYEO/UqUKKGAgAAlJyfb+wQFBTn0ufT9Up+C4PU/AADA7TnzheTjxo3TiBEjHNq8vLz+8XFzcnLUo0cP2Ww2zZ49+x8fzwSFJAAAgBN5eXkVSeH4R5eKyIMHD2rdunX2NFKSgoODlZqa6tD/woULSktLU3BwsL1PSkqKQ59L3y/1KQiWtgEAgNtz5j2SRe1SEblnzx59+eWXKl++vMP2iIgIpaena8uWLfa2devWKS8vT02aNLH3iY+PV05Ojr3PmjVrVLNmTZUrV67AY6GQBAAAKEYyMzOVlJSkpKQkSdKBAweUlJSkQ4cOKScnR/fee6++//57LV68WLm5uUpOTlZycrLOnz8vSapdu7bat2+vhx9+WJs3b9a3336rwYMHq2fPngoNDZUk9erVS56enurXr5927typpUuX6pVXXsm3BP93eP0PgGsKr/8BrmMufP3Pd3c47/U/TdcV7vU/69evV+vWrfO1R0dHKyYmRuHh4Zfd76uvvlKrVq0kXXwh+eDBg/XJJ5/IarWqe/fuiouLU5kyZez9t2/frkGDBikxMVEVKlTQkCFDNGbMmEKNlUISwDWFQhK4jlFIXnN42AYAALg9Jz60fV2jkAQAAG7P5DexwcM2AAAAMEQiCQAA3B6BpBkSSQAAABghkQQAAG6PeyTNkEgCAADACIkkAABwe1bLdfda7auCRBIAAABGSCQBAIDb4xZJMxSSAADA7fGwjRmWtgEAAGCERBIAALg9AkkzJJIAAAAwQiIJAADcHvdImiGRBAAAgBEKSbhcWOPb9cDsZRoZf1AxP+eoVpu7HLa3Gjxegz/boSe3pmvMplQ99NYq3fDvWx36hNRpoAfnfa6xm4/piY3J6jJptjxL+zj0Cb25sR6av1pjNx/TmE2p+s+bnyqo5r+dfn0A/mfJ+8vUpcdDanj7nWp4+526/6EB+npDQr5+NptN/QeNVM0GzfTlV/GXPdbJ9FNq0a6rajZopozTp509dFznrE78XM+u9+vDNaCkt49Sft6uTycNvez2E7/u0WeTh2n2XQ30VlQrpf9+UA/O+0yly1WQJJUNDNFDb61S2qF9euP+Znqnf2dVrF5HXWPn2Y/hWdpH/3lzpU4dPaw37m+mt6Ja6XzWaT345qeyluAOD+BqCQ6qqFFDHtXHi9/SR4vn6bZbG2nQ42O1Z99+h34LFy+V5W+WGp+aGKuaNao5cbQA/g7/BYXL7f1mtfZ+s/qK23esfM/h++rnR6nhfX0VVLOuDmz8Sje26qTcCzn6bNIQ2WwXf+JqZcwgPbZimwIqV1PaoX2qULWWSvuX11dxMcpI/k2StH7Ws3psxTb5h4Yp7dA+p10fgP+5o+XtDt8fH/yI3v1gmZK271SNalUlSbt2/6K3Fr2njxbP0+133nW5w2jJ+8t0+nSmHhvQR/HfbnT6uHH9+7v/44LLc2khefz4cb311ltKSEhQcnKyJCk4OFhNmzZV7969VbFiRVcOD8WQR8mSanR/f53LSFfKz9svtnl6KTfnvL2IlKQL585Kkio3aqa0Q/t0/MBunTl5XA3v7aNvXn9eFquHGnbvo2N7f1L677+64lIAt5ebm6tVa77SmbPn1ODfN0uSzp49p5HjJmrC2JGqWKH8Zffbu++AXntjvt5/e64O/37kag4Z1zEetjHjskIyMTFR7dq1U+nSpRUZGakbb7xRkpSSkqK4uDg9//zzWr16tRo3bvyXx8nOzlZ2drZD24U8m0rwv4jryo2tOureaYtV0ru0Th87qrf7dtCZ9BOSpAMbv1K7MS+qad8R2rToVZX09lHkyOckSWUqBkuSzmdlasFDkeo580O1GPiUJCnt4B4t6t9Jebm5rrkowE3t3rNPPaMfUfb58yrt7a1Z06aoerVwSVLstDg1qHezIls3v+y+58+f14hxMRo9fJBCQ4IpJAEXc1khOWTIEN13332aM2eOLH/Kk202mx599FENGTJECQn5b8L+o9jYWE2cONGhrWV5i1pV8CjyMcN1Dmxarzn3NFbpchXU8L5+um/GEr3Zo5my0o7p2N6ftHxcX7Ub86IiRzynvLxcbVo0U5nHkmXLy5MklfAqpbuenatD2xL04cgHZfXwUNO+jytqzn81974IXcg+5+IrBNxHeJXKWv7eAp3OzNTqL7/SmAnP6Z03Z+rg4d+0cfMWLXtv/hX3nRY3R9XCw3R3p3ZXccRwB8RPZiy2P64HXkXe3t7atm2batWqddntP//8sxo0aKCzZ8/+5XEul0hObRxAInmNivk5R+8N6q6f1674y35DVv2kbR8v0Ia5Ux3afcoHKudslmw2m8Z9n6YPR0Tpp9UfqUH3Pmrz+GRNa17JvgTuUbKkxmw6phVPD9CPn73vtGtC0YrZetTVQ0AR6/3IMFWudIO8vDy16N0PZbX+7znQ3NxcWa1WNW5QT4venKm774/WL3v32wMIm82mvLw8eXh46NF+D2nowP6uugwUhdIVXHbqXzo47/njGz/Pc9qxXc1liWRwcLA2b958xUJy8+bNCgoK+tvjeHl5ycvLy6GNIvL6Z7FaVcLTK1971olUSVKDbr11Ifuc9n/3pSSppHdp2fLyHO6jtOXlSTabLFZeXgC4Up4tT+fPn9eQR/vpvnscH67pct+DGjdyqFq3bCZJevWl53Qu+7x9+46du/RkzBQtnveaKle64aqOG9eXP6+OomBcVkiOGjVKAwYM0JYtW9SmTRt70ZiSkqK1a9fqjTfe0EsvveSq4eEq8izto4DK1e3f/f8VruBa9XT2VJrOpJ9Qi0fHafe6lTp97KhKl6ugW3sNlG/QDdq56iP7PrdGPabD2xJ0/kymqjaNVNvRz+vL6U/p3OlTkqT9336ptqOfV6cJr2rTO7NksVp1+8NPKC/3gg5sWn+1LxlwW9PiZqtFswiFhAQpK+uMVn7+hTZ/v03zXpuuihXKX/YBm9CQIFW6IVSSVLnSvxy2nUxPlyRVqxom37JlnT5+AI5cVkgOGjRIFSpU0Msvv6zXXntNuf//wIOHh4caNWqkBQsWqEePHq4aHq6i0Jsbqffba+3f24+7+H8gkpa9rZXPPKYK4TVVL+5BlS5XQWfTT+j3Hd/rrajWOrb3J/s+N9S9Ra2GTJBn6TI6vn+3PnnmMW1fsdi+/fiB3VoysKtaDRqv/u99I1teno7uStI7D3dW5rHkq3exgJs7kZauMeMnK/X4CZUt46OaNapr3mvT1ey2W/9+Z8CJCCTNuOweyT/KycnR8ePHJUkVKlRQyZIl/9HxYmr9s/0BFF/cIwlcx1x4j+TeTs57SLf6p9fv20GKxQvJS5YsqZCQEFcPAwAAuCsiSSPFopAEAABwJepIMzyuCgAAACMkkgAAwO3x+h8zJJIAAAAwQiIJAADcHomkGRJJAAAAGCGRBAAAIFozwrQBAADACIkkAABwe9wjaYZCEgAAuD3qSDMsbQMAAMAIiSQAAHB7LG2bIZEEAACAERJJAAAAAkkjJJIAAAAwQiIJAADcHvdImiGRBAAAgBESSQAA4PYIJM1QSAIAALfH0rYZlrYBAABghEQSAACARNIIiSQAAACMkEgCAAC3RyBphkQSAAAARkgkAQCA2+OpbTMkkgAAADBCIgkAANwegaQZEkkAAAAYIZEEAAAgkjRCIQkAANwedaQZlrYBAABghEQSAAC4PV7/Y4ZEEgAAAEZIJAEAgNsjkTRDIgkAAAAjJJIAAMDtEUiaIZEEAACAERJJAAAAIkkjFJIAAMDtUUeaYWkbAAAARkgkAQCA2+P1P2ZIJAEAAGCERBIAALg9AkkzJJIAAAAwQiIJAABAJGmERBIAAABGSCQBAIDb46ltMxSSAADA7VFHmmFpGwAAoBiJj49Xly5dFBoaKovFouXLlztst9lsmjBhgkJCQuTt7a3IyEjt2bPHoU9aWpqioqLk6+srf39/9evXT5mZmQ59tm/frubNm6tUqVKqVKmSpk6dWuixUkgCAAC3Z7FYnPYprKysLNWrV0+zZs267PapU6cqLi5Oc+bM0aZNm+Tj46N27drp3Llz9j5RUVHauXOn1qxZo5UrVyo+Pl4DBgywb8/IyFDbtm0VFhamLVu26MUXX1RMTIzmzp1buHmz2Wy2Ql9hMRdTq6SrhwDASWK2HnX1EAA4S+kKLjt1xkDnndt39nHjfS0Wi5YtW6auXbtKuphGhoaGauTIkRo1apQk6dSpUwoKCtKCBQvUs2dP7dq1S3Xq1FFiYqIaN24sSVq1apU6duyo3377TaGhoZo9e7aeeuopJScny9PTU5I0duxYLV++XD///HOBx0ciCQAAYHHeJzs7WxkZGQ6f7Oxso2EeOHBAycnJioyMtLf5+fmpSZMmSkhIkCQlJCTI39/fXkRKUmRkpKxWqzZt2mTv06JFC3sRKUnt2rXT7t27dfLkyQKPh0ISAADAiWJjY+Xn5+fwiY2NNTpWcnKyJCkoKMihPSgoyL4tOTlZgYGBDttLlCihgIAAhz6XO8Yfz1EQPLUNAADcnsXqvGxt3LhxGjFihEObl5eX0853NVFIAgAAOJGXl1eRFY7BwcGSpJSUFIWEhNjbU1JSVL9+fXuf1NRUh/0uXLigtLQ0+/7BwcFKSUlx6HPp+6U+BcHSNgAAgMXivE8RCg8PV3BwsNauXWtvy8jI0KZNmxQRESFJioiIUHp6urZs2WLvs27dOuXl5alJkyb2PvHx8crJybH3WbNmjWrWrKly5coVeDwUkgAAAMWokMzMzFRSUpKSkpIkXXzAJikpSYcOHZLFYtHw4cP17LPPasWKFdqxY4ceeughhYaG2p/srl27ttq3b6+HH35Ymzdv1rfffqvBgwerZ8+eCg0NlST16tVLnp6e6tevn3bu3KmlS5fqlVdeybcE/3dY2gYAAChGvv/+e7Vu3dr+/VJxFx0drQULFuiJJ55QVlaWBgwYoPT0dN1+++1atWqVSpUqZd9n8eLFGjx4sNq0aSOr1aru3bsrLi7Ovt3Pz09ffPGFBg0apEaNGqlChQqaMGGCw7smC4L3SAK4pvAeSeA65sL3SGYOC3Xascu8csRpx3Y1lrYBAABghKVtAACAIn4oxl2QSAIAAMAIiSQAAACJpBESSQAAABghkQQAAG7PQiJphEISAADAwiKtCWYNAAAARkgkAQCA27NYWdo2QSIJAAAAIySSAAAAPGxjhEQSAAAARkgkAQAAeGrbCLMGAAAAIySSAADA7fFCcjMUkgAAABSSRljaBgAAgBESSQAAABJJIySSAAAAMEIiCQAA3J6F1/8YYdYAAABghEQSAACAeySNkEgCAADACIkkAABwexYriaQJCkkAAAAetjHCrAEAAMAIiSQAAAAP2xghkQQAAIAREkkAAOD2LCSSRkgkAQAAYIREEgAAgETSSIEKyRUrVhT4gHfddZfxYAAAAHDtKFAh2bVr1wIdzGKxKDc395+MBwAA4OrjPZJGClRI5uXlOXscAAAALsPDNmYovwEAAGDE6GGbrKwsff311zp06JDOnz/vsG3o0KFFMjAAAICrht/aNlLoQnLbtm3q2LGjzpw5o6ysLAUEBOj48eMqXbq0AgMDKSQBAADcRKGXth9//HF16dJFJ0+elLe3tzZu3KiDBw+qUaNGeumll5wxRgAAAKeyWKxO+1zPCn11SUlJGjlypKxWqzw8PJSdna1KlSpp6tSpevLJJ50xRgAAABRDhS4kS5YsKav14m6BgYE6dOiQJMnPz0+HDx8u2tEBAABcDRaL8z7XsULfI9mgQQMlJiaqRo0aatmypSZMmKDjx49r0aJFuvnmm50xRgAAABRDhU4kp0yZopCQEEnSc889p3LlymngwIE6duyY5s6dW+QDBAAAcDoSSSOFTiQbN25s/3NgYKBWrVpVpAMCAADAtcHoPZIAAADXE37ZxkyhC8nw8PC/nOz9+/f/owEBAABcddf5a3qcpdCF5PDhwx2+5+TkaNu2bVq1apVGjx5dVOMCAABAMVfoQnLYsGGXbZ81a5a+//77fzwgAACAq46lbSNFluN26NBBH330UVEdDgAAAMVckT1s8+GHHyogIKCoDgcAAHDV8LCNGaMXkv9xsm02m5KTk3Xs2DG99tprRTo4AAAAFF+FLiTvvvtuh0LSarWqYsWKatWqlWrVqlWkgzMVk3jQ1UMA4CQr2wa5eggAnKTzhlzXndzKU9smCl1IxsTEOGEYAAAAuNYUuvz28PBQampqvvYTJ07Iw8OjSAYFAABwVfETiUYKnUjabLbLtmdnZ8vT0/MfDwgAAOCq44XkRgpcSMbFxUm6+FTTm2++qTJlyti35ebmKj4+vtjcIwkAAADnK3Ah+fLLL0u6mEjOmTPHYRnb09NTVapU0Zw5c4p+hAAAAM52nS9BO0uBC8kDBw5Iklq3bq2PP/5Y5cqVc9qgAAAAUPwV+h7Jr776yhnjAAAAcB3ukTRS6Fnr3r27XnjhhXztU6dO1X333VckgwIAAEDxV+hCMj4+Xh07dszX3qFDB8XHxxfJoAAAAK4qXv9jpNCFZGZm5mVf81OyZEllZGQUyaAAAABQ/BW6kKxbt66WLl2ar/29995TnTp1imRQAAAAV5XF6rzPdazQD9uMHz9e3bp10759+3THHXdIktauXaslS5boww8/LPIBAgAAON11vgTtLIUuJLt06aLly5drypQp+vDDD+Xt7a169epp3bp1CggIcMYYAQAAUAwVupCUpE6dOqlTp06SpIyMDL377rsaNWqUtmzZotzc3CIdIAAAgNNd50vQzmI8a/Hx8YqOjlZoaKimTZumO+64Qxs3bizKsQEAAKAYK1QimZycrAULFmjevHnKyMhQjx49lJ2dreXLl/OgDQAAuHZxj6SRAieSXbp0Uc2aNbV9+3bNmDFDR44c0auvvurMsQEAAKAYK3Ai+fnnn2vo0KEaOHCgatSo4cwxAQAAXF0kkkYKnEhu2LBBp0+fVqNGjdSkSRPNnDlTx48fd+bYAAAAUIwVuJC87bbb9MYbb+jo0aN65JFH9N577yk0NFR5eXlas2aNTp8+7cxxAgAAOA8vJDdS6Kvz8fFR3759tWHDBu3YsUMjR47U888/r8DAQN11113OGCMAAIBz8VvbRv5RmVyzZk1NnTpVv/32m959992iGhMAAACuAUYvJP8zDw8Pde3aVV27di2KwwEAAFxd1/kStLMwawAAADBSJIkkAADANe06v5fRWUgkAQAAYIRCEgAAoJi8/ic3N1fjx49XeHi4vL29Va1aNU2ePFk2m83ex2azacKECQoJCZG3t7ciIyO1Z88eh+OkpaUpKipKvr6+8vf3V79+/ZSZmVkkU/VHFJIAAADFxAsvvKDZs2dr5syZ2rVrl1544QVNnTrV4Wepp06dqri4OM2ZM0ebNm2Sj4+P2rVrp3Pnztn7REVFaefOnVqzZo1Wrlyp+Ph4DRgwoMjHa7H9scS9Xpw+4uoRAHCSlR0quXoIAJyk84Zcl507b/59Tju2tc8HBe7buXNnBQUFad68efa27t27y9vbW++8845sNptCQ0M1cuRIjRo1SpJ06tQpBQUFacGCBerZs6d27dqlOnXqKDExUY0bN5YkrVq1Sh07dtRvv/2m0NDQoru2IjsSAADAtcqJS9vZ2dnKyMhw+GRnZ192GE2bNtXatWv1yy+/SJJ++OEHbdiwQR06dJAkHThwQMnJyYqMjLTv4+fnpyZNmighIUGSlJCQIH9/f3sRKUmRkZGyWq3atGlTkU4bhSQAAIATxcbGys/Pz+ETGxt72b5jx45Vz549VatWLZUsWVINGjTQ8OHDFRUVJUlKTk6WJAUFBTnsFxQUZN+WnJyswMBAh+0lSpRQQECAvU9R4fU/AAAATnz9z7hx4zRixAiHNi8vr8v2ff/997V48WItWbJEN910k5KSkjR8+HCFhoYqOjraaWM0RSEJAADgRF5eXlcsHP9s9OjR9lRSkurWrauDBw8qNjZW0dHRCg4OliSlpKQoJCTEvl9KSorq168vSQoODlZqaqrDcS9cuKC0tDT7/kWFpW0AAIBi8vqfM2fOyGp13MfDw0N5eXmSpPDwcAUHB2vt2rX27RkZGdq0aZMiIiIkSREREUpPT9eWLVvsfdatW6e8vDw1adLEdIYui0QSAACgmOjSpYuee+45Va5cWTfddJO2bdum6dOnq2/fvpIki8Wi4cOH69lnn1WNGjUUHh6u8ePHKzQ0VF27dpUk1a5dW+3bt9fDDz+sOXPmKCcnR4MHD1bPnj2L9IltiUISAACg2PxE4quvvqrx48frscceU2pqqkJDQ/XII49owoQJ9j5PPPGEsrKyNGDAAKWnp+v222/XqlWrVKpUKXufxYsXa/DgwWrTpo2sVqu6d++uuLi4Ih8v75EEcE3hPZLA9cul75FcFOW0Y1sfXOy0Y7saiSQAAEAh72XERRSSAAAAxWRp+1pD+Q0AAAAjJJIAAAAsbRth1gAAAGCERBIAAIB7JI2QSAIAAMAIiSQAAAD3SBph1gAAAGCERBIAAIB7JI1QSAIAALC0bYRZAwAAgBESSQAAACtL2yZIJAEAAGCERBIAAICHbYyQSAIAAMAIiSQAAABPbRth1gAAAGCERBIAAIB7JI1QSAIAALC0bYRZAwAAgBESSQAAABJJI8waAAAAjJBIAgAAkEgaYdYAAABghEQSAACA1/8YIZEEAACAERJJAAAA7pE0QiEJAABAIWmEWQMAAIAREkkAAAAetjFCIgkAAAAjJJIAAADcI2mEWQMAAIAREkkAAAASSSPMGgAAAIyQSAIAAJBIGmHWAAAAYIREEgAAgPdIGqGQBAAAYGnbCLMGAAAAIySSAAAAJJJGmDUAAAAYIZEEAACwkq2ZYNYAAABghEQSAACA1/8YIZEEAACAERJJAAAAnto2QiEJAABAIWmEWQMAAIAREkkAAAAetjFCIgkAAAAjJJIAAADcI2mEWQMAAIAREkkAAAASSSPMGgAAAIyQSAIAAJBIGqGQBAAA4PU/Rii/AQAAYIREEgAAgKVtI8waAAAAjJBIAgAAkEgaYdYAAABghEQSAACAp7aNkEgCAADACIkkAAAA90gaoZAEAACgkDTCrAEAAMAIiSQAAACJpBFmDQAAAEZIJAEAAKy8/scEiSQAAACMkEii2Fny4X/17ocr9PvRZElSjapV9Fj/h9SyWRP9diRZbe564LL7zXj+GXWIbGX//vEnqzR/8Qf69dBhlfHxUfvIlnpmzPCrcAUALgmo11zVeo2SX82GKlUhVInjuinlm/9KkiweJVRzwGQF3tZBpUOr6kLWKR3/fq12zR6n7BNH7cdo/Pxy+dWoJ0//QOWcPvn/fcba+1g9vVR31Gz51WyoMmG1lfrdp/r+yW4uuV5cw7hH0giFJIqd4MCKGjX4YYVV/pdsNpuWr1ytQSOf1rLFc1W1SmVtWPWRQ/+lyz7RvEVL1aJpE3vb/Hfe11uLP9ATwx5RvZtr68zZc/r9SPLVvhTA7Xl4+yhj7w86/Ol8NZ7i+HfXo1Rp+d3YUHsWPqeMPT+opG853TTsZd3ywnJt6P+/v88ntn6lvYtilX38qEpVvEG1B01Vo2ff13cDm0uSLFYP5Waf1a8fzlRwKwpI4GqikESxc0eLpg7fHx/UX+9+tEJJO35SjWrhqlghwGH7l19tUIfIVvIp7S1JOpVxWjNmv6U5Lz+niFsb2fvVqlHN+YMH4ODYxlU6tnHVZbddyMrQpsfbObT9OH2omr+5SaWCKulcymFJ0oH3X7FvP5tySPvemarGsR/L4lFCttwLyj13Rj9OGyRJKle3qUqW8XfOxeD6RiJphEISxVpubq5Wffm1zpw9pwb/vinf9h937dauX/Zqwphh9rZvN32vPFueUlKPq8O90co6c0YN/n2Txg5/TCHBgVdz+AAKqWQZP9ny8nThdPrlt5ctpxva9tLJH7+TLffC1R0crm8UkkaK9awdPnxYffv2/cs+2dnZysjIcPhkZ2dfpRHCWXbv3a8GzTuobtO2eiZ2uma9OEnVq1bJ1+/D/36mauFhaljvZnvbb78flS3PpjnzF+vJkYMU98JEnco4rT6DRul8Ts5VvAoAhWH19FKtgbE68uV7unDmtMO2WgNj1X5Nhtp9flzeQZWUOPYeF40SwB8V60IyLS1NCxcu/Ms+sbGx8vPzc/jETpt5lUYIZwkPq6TlS97U+wte0wP33q0xMc9r7/5fHfqcO5etlavW6t67Ozq05+XlKefCBT09eoiaR9yq+nXraPpz43Xw8O/a9P22q3gVAArK4lFCDSctlUUW7XjpsXzb9y15Sd/0baSNw9vJlper+k//9X8bgEKzWJz3KaTff/9d//nPf1S+fHl5e3urbt26+v777+3bbTabJkyYoJCQEHl7eysyMlJ79uxxOEZaWpqioqLk6+srf39/9evXT5mZmf94mv7MpUvbK1as+Mvt+/fv/9tjjBs3TiNGjHBo8zp/4h+NC67nWbKkwirdIEm6uXZN7fjpZ7397kea9NRIe59Va7/WuXPZ6tqprcO+FSuUlyRVD69ibwso569y/n46mpzq/MEDKBSLRwk1mrxUpYMrK2FoZL40UpJyTp1QzqkTyjq8R5kHdyly2SH533Sb0ndudMGIAec5efKkmjVrptatW+vzzz9XxYoVtWfPHpUrV87eZ+rUqYqLi9PChQsVHh6u8ePHq127dvrpp59UqlQpSVJUVJSOHj2qNWvWKCcnR3369NGAAQO0ZMmSIh2vSwvJrl27ymKxyGazXbGP5W8qeS8vL3l5eTk2ni76ihuulZdny7cs/dF/P9MdLZoqoJy/Q/ulZe4DBw8pOKiiJCn9VIZOpp9SaEjQVRkvgIKxF5H/qq6NQ9soJyPt73eyXlxM8/D0+puOQGEUjxeSv/DCC6pUqZLmz59vbwsPD7f/2WazacaMGXr66ad19913S5LefvttBQUFafny5erZs6d27dqlVatWKTExUY0bN5Ykvfrqq+rYsaNeeuklhYaGFtl4Xbq0HRISoo8//lh5eXmX/WzdutWVw4OLTJv5hhK3/qDfjiRr9979mjbzDW3ekqQu7SPtfQ4e/l2J27br3q6d8u0fHlZJbVo203MvzdTWH37UL3sPaGzM86papZKaNG5wNS8FcHse3j7yrV5PvtXrSZJKh1SRb/V6KhVU6WIR+ewH8qvZSNsmPSiL1UNeAUHyCgiSpURJSZJ/nVtVpdtj8q1eT95BlVW+YWs1fGaxsn7bq5M/JtjPU6ZKbflWr6eSvgEqUcbX4ZyAqxXmeY4VK1aocePGuu+++xQYGKgGDRrojTfesG8/cOCAkpOTFRn5v/8m+vn5qUmTJkpIuPh3IiEhQf7+/vYiUpIiIyNltVq1adOmIr02lyaSjRo10pYtW+wV9Z/9XVqJ69OJtJMa80ysUo+nqWwZH9WsUVXzXp2qZrf97y/ERys+U3BgRd3+h7Y/mjpxnKZMn6VHho+T1WrVLQ3r6c24qSpZghcVAFeTf63Ginh1nf37TUOnS5IOf7ZQv7w1UcHN75IktVzgeP9ywpA7dGLb18o9d0bBLe/Rjf1i5FHKR9knjip102rtndBTeTnn7f1vfXGlSodUsX9vseBiELHydg9nXRquN058ajs2NlYTJ050aHvmmWcUExOTr+/+/fs1e/ZsjRgxQk8++aQSExM1dOhQeXp6Kjo6WsnJF9+JHBTkuMIWFBRk35acnKzAQMe3lJQoUUIBAQH2PkXFYnNhpfbNN98oKytL7du3v+z2rKwsff/992rZsmXhDnz6SBGMDkBxtLJDJVcPAYCTdN6Q67Jz5+1412nHzrmxW74E8rK35kny9PRU48aN9d1339nbhg4dqsTERCUkJOi7775Ts2bNdOTIEYWEhNj79OjRQxaLRUuXLtWUKVO0cOFC7d692+HYgYGBmjhxogYOHFhk1+bSeKZ58+Z/ud3Hx6fwRSQAAEBhGTxdXVBXKhovJyQkRHXq1HFoq127tj766OIvQwUHB0uSUlJSHArJlJQU1a9f394nNdXx4dILFy4oLS3Nvn9RKdav/wEAALg6rE78FFyzZs3yJYm//PKLwsLCJF188CY4OFhr1661b8/IyNCmTZsUEREhSYqIiFB6erq2bNli77Nu3Trl5eWpSZMmKkrcMAYAAFBMPP7442ratKmmTJmiHj16aPPmzZo7d67mzp0r6eLzI8OHD9ezzz6rGjVq2F//Exoaqq5du0q6mGC2b99eDz/8sObMmaOcnBwNHjxYPXv2LNIntiUKSQAAAKcubRfGLbfcomXLlmncuHGaNGmSwsPDNWPGDEVFRdn7PPHEE8rKytKAAQOUnp6u22+/XatWrbK/Q1KSFi9erMGDB6tNmzayWq3q3r274uLiiny8Ln3Yxml42Aa4bvGwDXD9cunDNjs/cNqxrTfd57RjuxqJJAAAQDFJJK81PGwDAAAAIySSAAAAZGtGmDUAAAAYIZEEAADgHkkjFJIAAAAUkkZY2gYAAIAREkkAAACyNSPMGgAAAIyQSAIAAHCPpBESSQAAABghkQQAALCQrZlg1gAAAGCERBIAAEDcI2mCQhIAAICHbYywtA0AAAAjJJIAAAA8bGOEWQMAAIAREkkAAOD2LNwjaYREEgAAAEZIJAEAAMjWjDBrAAAAMEIiCQAAwD2SRkgkAQAAYIREEgAAgETSCIUkAAAAi7RGmDUAAAAYIZEEAABgadsIiSQAAACMkEgCAACQSBohkQQAAIAREkkAAACyNSPMGgAAAIyQSAIAAHCPpBEKSQAAAAuLtCaYNQAAABghkQQAABBL2yZIJAEAAGCERBIAAICHbYyQSAIAAMAIiSQAAABPbRth1gAAAGCERBIAAIB7JI1QSAIAAPD6HyMsbQMAAMAIiSQAAAAP2xhh1gAAAGCERBIAAIB7JI2QSAIAAMAIiSQAAACv/zFCIgkAAAAjJJIAAADcI2mEQhIAAIClbSMsbQMAAMAIhSQAAACMUEgCAADACPdIAgAAcI+kERJJAAAAGCGRBAAA4PU/RkgkAQAAYIREEgAAgHskjVBIAgAAsLRthKVtAAAAGCGRBAAAYGnbCIkkAAAAjJBIAgAAcI+kERJJAAAAGCGRBAAA4B5JIySSAAAAMEIiCQAAwD2SRigkAQAAWNo2wtI2AAAAjJBIAgAAsLRthEQSAAAARigkAQAAYIRCEgAAAEYoJAEAgNuzWCxO+/wTzz//vCwWi4YPH25vO3funAYNGqTy5curTJky6t69u1JSUhz2O3TokDp16qTSpUsrMDBQo0eP1oULF/7RWC6HQhIAAKAYSkxM1Ouvv65///vfDu2PP/64PvnkE33wwQf6+uuvdeTIEXXr1s2+PTc3V506ddL58+f13XffaeHChVqwYIEmTJhQ5GOkkAQAAJDFiZ/Cy8zMVFRUlN544w2VK1fO3n7q1CnNmzdP06dP1x133KFGjRpp/vz5+u6777Rx40ZJ0hdffKGffvpJ77zzjurXr68OHTpo8uTJmjVrls6fP280niuhkAQAALBYnPbJzs5WRkaGwyc7O/svhzNo0CB16tRJkZGRDu1btmxRTk6OQ3utWrVUuXJlJSQkSJISEhJUt25dBQUF2fu0a9dOGRkZ2rlzZxFOGoUkAACAU8XGxsrPz8/hExsbe8X+7733nrZu3XrZPsnJyfL09JS/v79De1BQkJKTk+19/lhEXtp+aVtR4oXkAAAATnwh+bhx4zRixAiHNi8vr8v2PXz4sIYNG6Y1a9aoVKlSThtTUSGRBAAAcCIvLy/5+vo6fK5USG7ZskWpqalq2LChSpQooRIlSujrr79WXFycSpQooaCgIJ0/f17p6ekO+6WkpCg4OFiSFBwcnO8p7kvfL/UpKhSSAAAATrxHsjDatGmjHTt2KCkpyf5p3LixoqKi7H8uWbKk1q5da99n9+7dOnTokCIiIiRJERER2rFjh1JTU+191qxZI19fX9WpU6do5uv/sbQNAABQTJQtW1Y333yzQ5uPj4/Kly9vb+/Xr59GjBihgIAA+fr6asiQIYqIiNBtt90mSWrbtq3q1KmjBx98UFOnTlVycrKefvppDRo06IpJqCkKSQAAACfeI1nUXn75ZVmtVnXv3l3Z2dlq166dXnvtNft2Dw8PrVy5UgMHDlRERIR8fHwUHR2tSZMmFflYLDabzVbkR3W100dcPQIATrKyQyVXDwGAk3TekOu6k5867Lxj+12//26RSAIAAPzDnzJ0VxSSAAAA19DSdnHCU9sAAAAwQiIJAADA0rYREkkAAAAYIZEEAADgHkkjJJIAAAAwQiIJAABAIGmERBIAAABGSCQBAACIJI2QSAIAAMAIiSQAAADvkTRCIQkAAMDSthGWtgEAAGCERBIAAIClbSMkkgAAADBCIgkAAMA9kkZIJAEAAGDEYrPZbK4eBGAqOztbsbGxGjdunLy8vFw9HABFiL/fQPFHIYlrWkZGhvz8/HTq1Cn5+vq6ejgAihB/v4Hij6VtAAAAGKGQBAAAgBEKSQAAABihkMQ1zcvLS8888ww34gPXIf5+A8UfD9sAAADACIkkAAAAjFBIAgAAwAiFJAAAAIxQSAIAAMAIhSSuabNmzVKVKlVUqlQpNWnSRJs3b3b1kAD8Q/Hx8erSpYtCQ0NlsVi0fPlyVw8JwBVQSOKatXTpUo0YMULPPPOMtm7dqnr16qldu3ZKTU119dAA/ANZWVmqV6+eZs2a5eqhAPgbvP4H16wmTZrolltu0cyZMyVJeXl5qlSpkoYMGaKxY8e6eHQAioLFYtGyZcvUtWtXVw8FwGWQSOKadP78eW3ZskWRkZH2NqvVqsjISCUkJLhwZAAAuA8KSVyTjh8/rtzcXAUFBTm0BwUFKTk52UWjAgDAvVBIAgAAwAiFJK5JFSpUkIeHh1JSUhzaU1JSFBwc7KJRAQDgXigkcU3y9PRUo0aNtHbtWntbXl6e1q5dq4iICBeODAAA91HC1QMATI0YMULR0dFq3Lixbr31Vs2YMUNZWVnq06ePq4cG4B/IzMzU3r177d8PHDigpKQkBQQEqHLlyi4cGYA/4/U/uKbNnDlTL774opKTk1W/fn3FxcWpSZMmrh4WgH9g/fr1at26db726OhoLViw4OoPCMAVUUgCAADACPdIAgAAwAiFJAAAAIxQSAIAAMAIhSQAAACMUEgCAADACIUkAAAAjFBIAgAAwAiFJAAAAIxQSAIotnr37q2uXbvav7dq1UrDhw+/6uNYv369LBaL0tPTr/q5AaA4o5AEUGi9e/eWxWKRxWKRp6enqlevrkmTJunChQtOPe/HH3+syZMnF6gvxR8AOF8JVw8AwLWpffv2mj9/vrKzs/XZZ59p0KBBKlmypMaNG+fQ7/z58/L09CyScwYEBBTJcQAARYNEEoARLy8vBQcHKywsTAMHDlRkZKRWrFhhX45+7rnnFBoaqpo1a0qSDh8+rB49esjf318BAQG6++679euvv9qPl5ubqxEjRsjf31/ly5fXE088IZvN5nDOPy9tZ2dna8yYMapUqZK8vLxUvXp1zZs3T7/++qtat24tSSpXrpwsFot69+4tScrLy1NsbKzCw8Pl7e2tevXq6cMPP3Q4z2effaYbb7xR3t7eat26tcM4AQD/QyEJoEh4e3vr/PnzkqS1a9dq9+7dWrNmjVauXKmcnBy1a9dOZcuW1TfffKNvv/1WZcqUUfv27e37TJs2TQsWLNBbb72lDRs2KC0tTcuWLfvLcz700EN69913FRcXp127dun1119XmTJlVKlSJX300UeSpN27d+vo0aN65ZVXJEmxsbF6++23NWfOHO3cuVOPP/64/vOf/+jrr7+WdLHg7datm7p06aKkpCT1799fY8eOdda0AcA1jaVtAP+IzWbT2rVrtXr1ag0ZMkTHjh2Tj4+P3nzzTfuS9jvvvKO8vDy9+eabslgskqT58+fL399f69evV9u2bTVjxgyNGzdO3bp1kyTNmTNHq1evvuJ5f/nlF73//vtas2aNIiMjJUlVq1a1b7+0DB4YGCh/f39JFxPMKVOm6Msvv1RERIR9nw0bNuj1119Xy5YtNXv2bFWrVk3Tpk2TJNWsWVM7duzQCy+8UISzBgDXBwpJAEZWrlypMmXKKCcnR3l5eerVq5diYmI0aNAg1a1b1+G+yB9++EF79+5V2bJlHY5x7tw57du3T6dOndLRo0fVpEkT+7YSJUqocePG+Za3L0lKSpKHh4datmxZ4DHv3btXZ86c0Z133unQfv78eTVo0ECStGvXLodxSLIXnQAARxSSAIy0bt1as2fPlqenp0JDQ1WixP/+OfHx8XHom5mZqUaNGmnx4sX5jlOxYkWj83t7exd6n8zMTEnSp59+qhtuuMFhm5eXl9E4AMCdUUgCMOLj46Pq1asXqG/Dhg21dOlSBQYGytfX97J9QkJCtGnTJrVo0UKSdOHCBW3ZskUNGza8bP+6desqLy9PX3/9tX1p+48uJaK5ubn2tjp16sjLy0uHDh26YpJZu3ZtrVixwqFt48aNf3+RAOCGeNgGgNNFRUWpQoUKuvvuu/XNN9/owIEDWr9+vYYOHarffvtNkjRs2DA9//zzWr58uX7++Wc99thjf/kOyCpVqig6Olp9+/bV8uXL7cd8//33JUlhYWGyWCxauXKljh07pszMTJUtW1ajRo3S448/roULF2rfvn3aunWrXn31VS1cuFCS9Oijj2rPnj0aPXq0du/erSVLlmjBggXOniIAuCZRSAJwutKlSys+Pl6VK1dWt27dVLt2bfXr10/nzp2zJ5QjR47Ugw8+qOjoaEVERKhs2bK65557/vK4s2fP1r333qvHHntMtWrV0sMPP6ysrCxJ0g033KCJEydq7NixCgoK0uDBgyVJkydP1vjx4xUbG6vatWurffv2+vTTTxUeHi5Jqly5sj766CMtX75c9erV05w5czRlyhQnzg4AXLsstivdyQ4AAAD8BRJJAAAAGKGQBAAAgBEKSQAAABihkAQAAIARCkkAAAAYoZAEAACAEQpJAAAAGKGQBAAAgBEKSQAAABihkAQAAIARCkkAAAAY+T+BRFLPlzgi9gAAAABJRU5ErkJggg==\n"
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "tree_structure = export_text(clf, feature_names=list(X.columns))\n",
        "print(\"Decision Tree Structure:\")\n",
        "print(tree_structure)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "A0NPIDK0wcRk",
        "outputId": "a646762a-90a5-4c8e-ccb2-ff1a005f280f"
      },
      "execution_count": 27,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Decision Tree Structure:\n",
            "|--- duration <= 251.50\n",
            "|   |--- poutcome_success <= 0.50\n",
            "|   |   |--- duration <= 123.50\n",
            "|   |   |   |--- month_mar <= 0.50\n",
            "|   |   |   |   |--- month_oct <= 0.50\n",
            "|   |   |   |   |   |--- month_feb <= 0.50\n",
            "|   |   |   |   |   |   |--- job_student <= 0.50\n",
            "|   |   |   |   |   |   |   |--- day <= 1.50\n",
            "|   |   |   |   |   |   |   |   |--- age <= 36.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- age >  36.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- day >  1.50\n",
            "|   |   |   |   |   |   |   |   |--- duration <= 88.50\n",
            "|   |   |   |   |   |   |   |   |   |--- month_sep <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- campaign <= 1.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 9\n",
            "|   |   |   |   |   |   |   |   |   |   |--- campaign >  1.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4\n",
            "|   |   |   |   |   |   |   |   |   |--- month_sep >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- campaign <= 2.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- campaign >  2.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- duration >  88.50\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays <= 478.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_sep <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 14\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_sep >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays >  478.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- job_student >  0.50\n",
            "|   |   |   |   |   |   |   |--- month_may <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- age <= 31.00\n",
            "|   |   |   |   |   |   |   |   |   |--- month_jun <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- month_jun >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day <= 18.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day >  18.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- age >  31.00\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- month_may >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |--- month_feb >  0.50\n",
            "|   |   |   |   |   |   |--- day <= 10.00\n",
            "|   |   |   |   |   |   |   |--- duration <= 122.50\n",
            "|   |   |   |   |   |   |   |   |--- age <= 29.50\n",
            "|   |   |   |   |   |   |   |   |   |--- education_tertiary <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- education_tertiary >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance <= 387.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance >  387.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- age >  29.50\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= -15.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance <= -165.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance >  -165.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  -15.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- duration >  122.50\n",
            "|   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- day >  10.00\n",
            "|   |   |   |   |   |   |   |--- balance <= 185.00\n",
            "|   |   |   |   |   |   |   |   |--- job_technician <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- job_technician >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- balance >  185.00\n",
            "|   |   |   |   |   |   |   |   |--- education_unknown <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 62.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  62.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- housing_yes <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- housing_yes >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- education_unknown >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |--- month_oct >  0.50\n",
            "|   |   |   |   |   |--- age <= 43.00\n",
            "|   |   |   |   |   |   |--- day <= 26.50\n",
            "|   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |--- day >  26.50\n",
            "|   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |--- age >  43.00\n",
            "|   |   |   |   |   |   |--- balance <= 196.00\n",
            "|   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |--- balance >  196.00\n",
            "|   |   |   |   |   |   |   |--- job_technician <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- marital_single <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- marital_single >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- job_technician >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |--- month_mar >  0.50\n",
            "|   |   |   |   |--- poutcome_other <= 0.50\n",
            "|   |   |   |   |   |--- age <= 62.00\n",
            "|   |   |   |   |   |   |--- job_services <= 0.50\n",
            "|   |   |   |   |   |   |   |--- age <= 29.50\n",
            "|   |   |   |   |   |   |   |   |--- day <= 4.00\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- day >  4.00\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- age >  29.50\n",
            "|   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- job_services >  0.50\n",
            "|   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |--- age >  62.00\n",
            "|   |   |   |   |   |   |--- age <= 69.00\n",
            "|   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |--- age >  69.00\n",
            "|   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |--- poutcome_other >  0.50\n",
            "|   |   |   |   |   |--- class: no\n",
            "|   |   |--- duration >  123.50\n",
            "|   |   |   |--- contact_unknown <= 0.50\n",
            "|   |   |   |   |--- housing_yes <= 0.50\n",
            "|   |   |   |   |   |--- month_aug <= 0.50\n",
            "|   |   |   |   |   |   |--- month_jul <= 0.50\n",
            "|   |   |   |   |   |   |   |--- month_nov <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- month_jan <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- month_feb <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_may <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 20\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_may >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 8\n",
            "|   |   |   |   |   |   |   |   |   |--- month_feb >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day <= 7.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 11\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day >  7.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |   |--- month_jan >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- day <= 27.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- day >  27.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance <= 1643.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance >  1643.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |--- month_nov >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- day <= 16.50\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= 154.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration <= 217.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration >  217.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  154.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_retired <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_retired >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |--- day >  16.50\n",
            "|   |   |   |   |   |   |   |   |   |--- day <= 23.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day <= 17.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day >  17.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- day >  23.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- month_jul >  0.50\n",
            "|   |   |   |   |   |   |   |--- pdays <= 200.00\n",
            "|   |   |   |   |   |   |   |   |--- day <= 6.50\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= 2.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  2.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- day >  6.50\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 26.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_services <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_services >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  26.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- previous <= 1.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 9\n",
            "|   |   |   |   |   |   |   |   |   |   |--- previous >  1.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |--- pdays >  200.00\n",
            "|   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |--- month_aug >  0.50\n",
            "|   |   |   |   |   |   |--- pdays <= 32.00\n",
            "|   |   |   |   |   |   |   |--- campaign <= 1.50\n",
            "|   |   |   |   |   |   |   |   |--- duration <= 183.00\n",
            "|   |   |   |   |   |   |   |   |   |--- job_unemployed <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day <= 13.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day >  13.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |--- job_unemployed >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- duration >  183.00\n",
            "|   |   |   |   |   |   |   |   |   |--- day <= 27.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_technician <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_technician >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- day >  27.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- campaign >  1.50\n",
            "|   |   |   |   |   |   |   |   |--- age <= 26.50\n",
            "|   |   |   |   |   |   |   |   |   |--- duration <= 164.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- duration >  164.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- age >  26.50\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 62.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_retired <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 6\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_retired >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  62.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- pdays >  32.00\n",
            "|   |   |   |   |   |   |   |--- job_unemployed <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- pdays <= 586.00\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= 31.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- poutcome_other <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |   |--- poutcome_other >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  31.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- pdays >  586.00\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- job_unemployed >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |--- housing_yes >  0.50\n",
            "|   |   |   |   |   |--- month_jun <= 0.50\n",
            "|   |   |   |   |   |   |--- month_mar <= 0.50\n",
            "|   |   |   |   |   |   |   |--- month_oct <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- pdays <= 1.50\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 59.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_sep <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 16\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_sep >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  59.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_blue-collar <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_blue-collar >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- pdays >  1.50\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays <= 97.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_management <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_management >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays >  97.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_aug <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 9\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_aug >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |--- month_oct >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- age <= 43.00\n",
            "|   |   |   |   |   |   |   |   |   |--- campaign <= 3.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- campaign >  3.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- age >  43.00\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 67.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  67.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- month_mar >  0.50\n",
            "|   |   |   |   |   |   |   |--- poutcome_other <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- campaign <= 3.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- campaign >  3.50\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 32.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  32.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- poutcome_other >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |--- month_jun >  0.50\n",
            "|   |   |   |   |   |   |--- duration <= 141.00\n",
            "|   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |--- duration >  141.00\n",
            "|   |   |   |   |   |   |   |--- education_tertiary <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- education_tertiary >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- balance <= 706.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- balance >  706.50\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 42.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  42.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |--- contact_unknown >  0.50\n",
            "|   |   |   |   |--- month_oct <= 0.50\n",
            "|   |   |   |   |   |--- month_nov <= 0.50\n",
            "|   |   |   |   |   |   |--- age <= 26.50\n",
            "|   |   |   |   |   |   |   |--- job_management <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- housing_yes <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= 95.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  95.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- housing_yes >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- job_management >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- age >  26.50\n",
            "|   |   |   |   |   |   |   |--- month_jul <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- day <= 2.50\n",
            "|   |   |   |   |   |   |   |   |   |--- duration <= 228.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- duration >  228.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- day >  2.50\n",
            "|   |   |   |   |   |   |   |   |   |--- job_blue-collar <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- job_blue-collar >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day <= 5.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day >  5.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4\n",
            "|   |   |   |   |   |   |   |--- month_jul >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- education_secondary <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- education_secondary >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= 862.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  862.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |--- month_nov >  0.50\n",
            "|   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |--- month_oct >  0.50\n",
            "|   |   |   |   |   |--- class: yes\n",
            "|   |--- poutcome_success >  0.50\n",
            "|   |   |--- duration <= 79.50\n",
            "|   |   |   |--- balance <= 1742.00\n",
            "|   |   |   |   |--- class: no\n",
            "|   |   |   |--- balance >  1742.00\n",
            "|   |   |   |   |--- duration <= 68.00\n",
            "|   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |--- duration >  68.00\n",
            "|   |   |   |   |   |--- class: yes\n",
            "|   |   |--- duration >  79.50\n",
            "|   |   |   |--- duration <= 147.00\n",
            "|   |   |   |   |--- duration <= 145.50\n",
            "|   |   |   |   |   |--- contact_telephone <= 0.50\n",
            "|   |   |   |   |   |   |--- pdays <= 82.50\n",
            "|   |   |   |   |   |   |   |--- balance <= 98.00\n",
            "|   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- balance >  98.00\n",
            "|   |   |   |   |   |   |   |   |--- month_jun <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- month_jun >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 43.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  43.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |--- pdays >  82.50\n",
            "|   |   |   |   |   |   |   |--- pdays <= 99.50\n",
            "|   |   |   |   |   |   |   |   |--- duration <= 86.50\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays <= 93.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays >  93.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- duration >  86.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- pdays >  99.50\n",
            "|   |   |   |   |   |   |   |   |--- housing_yes <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- day <= 13.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- pdays <= 182.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- pdays >  182.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |--- day >  13.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- previous <= 6.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5\n",
            "|   |   |   |   |   |   |   |   |   |   |--- previous >  6.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- housing_yes >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |--- contact_telephone >  0.50\n",
            "|   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |--- duration >  145.50\n",
            "|   |   |   |   |   |--- class: no\n",
            "|   |   |   |--- duration >  147.00\n",
            "|   |   |   |   |--- previous <= 21.00\n",
            "|   |   |   |   |   |--- pdays <= 508.00\n",
            "|   |   |   |   |   |   |--- campaign <= 3.50\n",
            "|   |   |   |   |   |   |   |--- age <= 47.50\n",
            "|   |   |   |   |   |   |   |   |--- pdays <= 82.50\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays <= 81.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_may <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_may >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays >  81.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- pdays >  82.50\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 39.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_aug <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_aug >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  39.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance <= 803.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance >  803.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- age >  47.50\n",
            "|   |   |   |   |   |   |   |   |--- month_jun <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- marital_single <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_unknown <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_unknown >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- marital_single >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- month_jun >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays <= 81.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays >  81.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |--- campaign >  3.50\n",
            "|   |   |   |   |   |   |   |--- duration <= 160.00\n",
            "|   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- duration >  160.00\n",
            "|   |   |   |   |   |   |   |   |--- day <= 6.00\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- day >  6.00\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |--- pdays >  508.00\n",
            "|   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |--- previous >  21.00\n",
            "|   |   |   |   |   |--- class: no\n",
            "|--- duration >  251.50\n",
            "|   |--- duration <= 474.50\n",
            "|   |   |--- contact_unknown <= 0.50\n",
            "|   |   |   |--- poutcome_success <= 0.50\n",
            "|   |   |   |   |--- housing_yes <= 0.50\n",
            "|   |   |   |   |   |--- loan_yes <= 0.50\n",
            "|   |   |   |   |   |   |--- month_aug <= 0.50\n",
            "|   |   |   |   |   |   |   |--- month_jul <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- month_jan <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- month_nov <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day <= 14.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 12\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day >  14.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 12\n",
            "|   |   |   |   |   |   |   |   |   |--- month_nov >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day <= 16.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day >  16.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 9\n",
            "|   |   |   |   |   |   |   |   |--- month_jan >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- day <= 27.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- day >  27.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance <= -248.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance >  -248.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5\n",
            "|   |   |   |   |   |   |   |--- month_jul >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- duration <= 308.50\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 60.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- education_unknown <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 6\n",
            "|   |   |   |   |   |   |   |   |   |   |--- education_unknown >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  60.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- duration >  308.50\n",
            "|   |   |   |   |   |   |   |   |   |--- day <= 8.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- campaign <= 6.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |   |--- campaign >  6.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- day >  8.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration <= 422.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 6\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration >  422.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- month_aug >  0.50\n",
            "|   |   |   |   |   |   |   |--- campaign <= 1.50\n",
            "|   |   |   |   |   |   |   |   |--- day <= 21.50\n",
            "|   |   |   |   |   |   |   |   |   |--- duration <= 341.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration <= 310.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration >  310.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |   |   |--- duration >  341.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- day >  21.50\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= 1036.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  1036.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- campaign >  1.50\n",
            "|   |   |   |   |   |   |   |   |--- age <= 59.50\n",
            "|   |   |   |   |   |   |   |   |   |--- duration <= 361.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- pdays <= 152.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 10\n",
            "|   |   |   |   |   |   |   |   |   |   |--- pdays >  152.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- duration >  361.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance <= 2.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance >  2.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 7\n",
            "|   |   |   |   |   |   |   |   |--- age >  59.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |--- loan_yes >  0.50\n",
            "|   |   |   |   |   |   |--- duration <= 414.00\n",
            "|   |   |   |   |   |   |   |--- balance <= 116.00\n",
            "|   |   |   |   |   |   |   |   |--- day <= 1.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- day >  1.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- balance >  116.00\n",
            "|   |   |   |   |   |   |   |   |--- month_sep <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- duration <= 370.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age <= 61.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age >  61.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- duration >  370.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- month_sep >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- duration >  414.00\n",
            "|   |   |   |   |   |   |   |--- campaign <= 3.50\n",
            "|   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- campaign >  3.50\n",
            "|   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |--- housing_yes >  0.50\n",
            "|   |   |   |   |   |--- pdays <= 374.50\n",
            "|   |   |   |   |   |   |--- month_jun <= 0.50\n",
            "|   |   |   |   |   |   |   |--- duration <= 392.50\n",
            "|   |   |   |   |   |   |   |   |--- month_mar <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- month_sep <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day <= 29.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 19\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day >  29.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4\n",
            "|   |   |   |   |   |   |   |   |   |--- month_sep >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- month_mar >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- duration >  392.50\n",
            "|   |   |   |   |   |   |   |   |--- duration <= 460.00\n",
            "|   |   |   |   |   |   |   |   |   |--- job_blue-collar <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration <= 453.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 14\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration >  453.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- job_blue-collar >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance <= 622.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance >  622.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4\n",
            "|   |   |   |   |   |   |   |   |--- duration >  460.00\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= 1227.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_management <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_management >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  1227.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- previous <= 6.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |   |--- previous >  6.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |--- month_jun >  0.50\n",
            "|   |   |   |   |   |   |   |--- job_services <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- job_services >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- age <= 40.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- age >  40.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |--- pdays >  374.50\n",
            "|   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |--- poutcome_success >  0.50\n",
            "|   |   |   |   |--- previous <= 10.50\n",
            "|   |   |   |   |   |--- campaign <= 4.50\n",
            "|   |   |   |   |   |   |--- month_jun <= 0.50\n",
            "|   |   |   |   |   |   |   |--- pdays <= 186.50\n",
            "|   |   |   |   |   |   |   |   |--- month_nov <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- month_nov >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- job_technician <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- job_technician >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- pdays <= 92.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |   |--- pdays >  92.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- pdays >  186.50\n",
            "|   |   |   |   |   |   |   |   |--- age <= 74.50\n",
            "|   |   |   |   |   |   |   |   |   |--- month_jan <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day <= 2.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day >  2.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- month_jan >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_retired <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_retired >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- age >  74.50\n",
            "|   |   |   |   |   |   |   |   |   |--- previous <= 5.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- previous >  5.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- month_jun >  0.50\n",
            "|   |   |   |   |   |   |   |--- previous <= 6.50\n",
            "|   |   |   |   |   |   |   |   |--- balance <= 4454.00\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= 219.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_blue-collar <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_blue-collar >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  219.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- balance >  4454.00\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- previous >  6.50\n",
            "|   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |--- campaign >  4.50\n",
            "|   |   |   |   |   |   |--- balance <= 3110.50\n",
            "|   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- balance >  3110.50\n",
            "|   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |--- previous >  10.50\n",
            "|   |   |   |   |   |--- marital_married <= 0.50\n",
            "|   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |--- marital_married >  0.50\n",
            "|   |   |   |   |   |   |--- class: no\n",
            "|   |   |--- contact_unknown >  0.50\n",
            "|   |   |   |--- poutcome_unknown <= 0.50\n",
            "|   |   |   |   |--- class: yes\n",
            "|   |   |   |--- poutcome_unknown >  0.50\n",
            "|   |   |   |   |--- month_oct <= 0.50\n",
            "|   |   |   |   |   |--- duration <= 380.50\n",
            "|   |   |   |   |   |   |--- month_nov <= 0.50\n",
            "|   |   |   |   |   |   |   |--- age <= 50.50\n",
            "|   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- age >  50.50\n",
            "|   |   |   |   |   |   |   |   |--- job_services <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 51.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_may <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_may >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  51.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- job_services >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- month_nov >  0.50\n",
            "|   |   |   |   |   |   |   |--- job_retired <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- job_retired >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |--- duration >  380.50\n",
            "|   |   |   |   |   |   |--- default_yes <= 0.50\n",
            "|   |   |   |   |   |   |   |--- job_entrepreneur <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- duration <= 472.50\n",
            "|   |   |   |   |   |   |   |   |   |--- day <= 2.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- day >  2.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- campaign <= 1.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5\n",
            "|   |   |   |   |   |   |   |   |   |   |--- campaign >  1.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 6\n",
            "|   |   |   |   |   |   |   |   |--- duration >  472.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- job_entrepreneur >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- default_yes >  0.50\n",
            "|   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |--- month_oct >  0.50\n",
            "|   |   |   |   |   |--- class: yes\n",
            "|   |--- duration >  474.50\n",
            "|   |   |--- duration <= 648.50\n",
            "|   |   |   |--- contact_unknown <= 0.50\n",
            "|   |   |   |   |--- poutcome_success <= 0.50\n",
            "|   |   |   |   |   |--- month_nov <= 0.50\n",
            "|   |   |   |   |   |   |--- month_jul <= 0.50\n",
            "|   |   |   |   |   |   |   |--- month_jun <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- duration <= 609.50\n",
            "|   |   |   |   |   |   |   |   |   |--- housing_yes <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration <= 604.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 12\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration >  604.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |   |   |--- housing_yes >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age <= 35.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 8\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age >  35.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 10\n",
            "|   |   |   |   |   |   |   |   |--- duration >  609.50\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 62.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day <= 2.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day >  2.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  62.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- pdays <= 185.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- pdays >  185.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- month_jun >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- month_jul >  0.50\n",
            "|   |   |   |   |   |   |   |--- job_blue-collar <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- balance <= 1933.00\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 32.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration <= 488.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration >  488.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  32.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_management <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 9\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_management >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |   |--- balance >  1933.00\n",
            "|   |   |   |   |   |   |   |   |   |--- duration <= 502.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- duration >  502.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- job_blue-collar >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- education_tertiary <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- campaign <= 6.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- campaign >  6.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration <= 585.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration >  585.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- education_tertiary >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |--- month_nov >  0.50\n",
            "|   |   |   |   |   |   |--- duration <= 629.00\n",
            "|   |   |   |   |   |   |   |--- day <= 19.50\n",
            "|   |   |   |   |   |   |   |   |--- contact_telephone <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= 55.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  55.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- previous <= 1.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 6\n",
            "|   |   |   |   |   |   |   |   |   |   |--- previous >  1.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |--- contact_telephone >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- day >  19.50\n",
            "|   |   |   |   |   |   |   |   |--- balance <= 12433.50\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= 734.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance <= 174.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance >  174.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  734.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- balance >  12433.50\n",
            "|   |   |   |   |   |   |   |   |   |--- job_management <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- job_management >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- duration >  629.00\n",
            "|   |   |   |   |   |   |   |--- duration <= 642.50\n",
            "|   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- duration >  642.50\n",
            "|   |   |   |   |   |   |   |   |--- age <= 32.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- age >  32.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |--- poutcome_success >  0.50\n",
            "|   |   |   |   |   |--- job_student <= 0.50\n",
            "|   |   |   |   |   |   |--- balance <= 13362.50\n",
            "|   |   |   |   |   |   |   |--- day <= 3.50\n",
            "|   |   |   |   |   |   |   |   |--- month_jul <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- month_jul >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- day >  3.50\n",
            "|   |   |   |   |   |   |   |   |--- pdays <= 67.50\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays <= 57.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays >  57.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- pdays >  67.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- balance >  13362.50\n",
            "|   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |--- job_student >  0.50\n",
            "|   |   |   |   |   |   |--- duration <= 526.50\n",
            "|   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |--- duration >  526.50\n",
            "|   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |--- contact_unknown >  0.50\n",
            "|   |   |   |   |--- month_may <= 0.50\n",
            "|   |   |   |   |   |--- balance <= 2910.50\n",
            "|   |   |   |   |   |   |--- balance <= 273.50\n",
            "|   |   |   |   |   |   |   |--- job_entrepreneur <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- day <= 3.50\n",
            "|   |   |   |   |   |   |   |   |   |--- campaign <= 2.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance <= 136.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- balance >  136.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- campaign >  2.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- day >  3.50\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 50.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  50.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration <= 540.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration >  540.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- job_entrepreneur >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |--- balance >  273.50\n",
            "|   |   |   |   |   |   |   |--- campaign <= 2.50\n",
            "|   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- campaign >  2.50\n",
            "|   |   |   |   |   |   |   |   |--- balance <= 2076.50\n",
            "|   |   |   |   |   |   |   |   |   |--- duration <= 597.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- duration >  597.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age <= 38.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age >  38.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- balance >  2076.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |--- balance >  2910.50\n",
            "|   |   |   |   |   |   |--- marital_married <= 0.50\n",
            "|   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- marital_married >  0.50\n",
            "|   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |--- month_may >  0.50\n",
            "|   |   |   |   |   |--- balance <= 1488.50\n",
            "|   |   |   |   |   |   |--- age <= 57.50\n",
            "|   |   |   |   |   |   |   |--- duration <= 519.00\n",
            "|   |   |   |   |   |   |   |   |--- education_unknown <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= 791.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration <= 485.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration >  485.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  791.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- education_unknown >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- duration >  519.00\n",
            "|   |   |   |   |   |   |   |   |--- balance <= -439.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- balance >  -439.50\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= 57.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age <= 42.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age >  42.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  57.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age <= 51.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age >  51.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |--- age >  57.50\n",
            "|   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |--- balance >  1488.50\n",
            "|   |   |   |   |   |   |--- balance <= 4907.50\n",
            "|   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |--- balance >  4907.50\n",
            "|   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |--- duration >  648.50\n",
            "|   |   |   |--- balance <= 19640.00\n",
            "|   |   |   |   |--- day <= 3.50\n",
            "|   |   |   |   |   |--- pdays <= 201.50\n",
            "|   |   |   |   |   |   |--- job_self-employed <= 0.50\n",
            "|   |   |   |   |   |   |   |--- job_management <= 0.50\n",
            "|   |   |   |   |   |   |   |   |--- month_oct <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 42.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_housemaid <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_housemaid >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  42.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- month_oct >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- job_management >  0.50\n",
            "|   |   |   |   |   |   |   |   |--- education_tertiary <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- education_tertiary >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- campaign <= 4.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- campaign >  4.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |--- job_self-employed >  0.50\n",
            "|   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |--- pdays >  201.50\n",
            "|   |   |   |   |   |   |--- pdays <= 266.50\n",
            "|   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |--- pdays >  266.50\n",
            "|   |   |   |   |   |   |   |--- day <= 2.50\n",
            "|   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- day >  2.50\n",
            "|   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |--- day >  3.50\n",
            "|   |   |   |   |   |--- duration <= 922.50\n",
            "|   |   |   |   |   |   |--- balance <= 1911.00\n",
            "|   |   |   |   |   |   |   |--- balance <= 1841.50\n",
            "|   |   |   |   |   |   |   |   |--- marital_married <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- poutcome_other <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration <= 915.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 13\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration >  915.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- poutcome_other >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration <= 817.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration >  817.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- marital_married >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays <= 4.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_feb <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 13\n",
            "|   |   |   |   |   |   |   |   |   |   |--- month_feb >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays >  4.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_self-employed <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4\n",
            "|   |   |   |   |   |   |   |   |   |   |--- job_self-employed >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |--- balance >  1841.50\n",
            "|   |   |   |   |   |   |   |   |--- month_aug <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- month_aug >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- balance >  1911.00\n",
            "|   |   |   |   |   |   |   |--- day <= 14.50\n",
            "|   |   |   |   |   |   |   |   |--- age <= 69.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- age >  69.50\n",
            "|   |   |   |   |   |   |   |   |   |--- age <= 70.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- age >  70.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- day >  14.50\n",
            "|   |   |   |   |   |   |   |   |--- day <= 17.50\n",
            "|   |   |   |   |   |   |   |   |   |--- campaign <= 2.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration <= 709.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration >  709.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |   |   |--- campaign >  2.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |--- day >  17.50\n",
            "|   |   |   |   |   |   |   |   |   |--- job_self-employed <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration <= 920.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5\n",
            "|   |   |   |   |   |   |   |   |   |   |--- duration >  920.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2\n",
            "|   |   |   |   |   |   |   |   |   |--- job_self-employed >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day <= 27.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- day >  27.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |--- duration >  922.50\n",
            "|   |   |   |   |   |   |--- duration <= 1081.50\n",
            "|   |   |   |   |   |   |   |--- previous <= 7.50\n",
            "|   |   |   |   |   |   |   |   |--- month_oct <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= -685.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age <= 35.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age >  35.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  -685.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- contact_unknown <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5\n",
            "|   |   |   |   |   |   |   |   |   |   |--- contact_unknown >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 6\n",
            "|   |   |   |   |   |   |   |   |--- month_oct >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- job_retired <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |--- job_retired >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |--- previous >  7.50\n",
            "|   |   |   |   |   |   |   |   |--- marital_single <= 0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- marital_single >  0.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |--- duration >  1081.50\n",
            "|   |   |   |   |   |   |   |--- age <= 64.50\n",
            "|   |   |   |   |   |   |   |   |--- duration <= 1083.50\n",
            "|   |   |   |   |   |   |   |   |   |--- balance <= 155.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- balance >  155.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- duration >  1083.50\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays <= 315.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age <= 30.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age >  30.50\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 19\n",
            "|   |   |   |   |   |   |   |   |   |--- pdays >  315.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age <= 30.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |   |   |--- age >  30.00\n",
            "|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3\n",
            "|   |   |   |   |   |   |   |--- age >  64.50\n",
            "|   |   |   |   |   |   |   |   |--- previous <= 1.50\n",
            "|   |   |   |   |   |   |   |   |   |--- duration <= 1129.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |   |   |   |   |   |   |--- duration >  1129.00\n",
            "|   |   |   |   |   |   |   |   |   |   |--- class: no\n",
            "|   |   |   |   |   |   |   |   |--- previous >  1.50\n",
            "|   |   |   |   |   |   |   |   |   |--- class: yes\n",
            "|   |   |   |--- balance >  19640.00\n",
            "|   |   |   |   |--- class: no\n",
            "\n"
          ]
        }
      ]
    }
  ]
}

{'nbformat': 4,
 'nbformat_minor': 0,
 'metadata': {'colab': {'provenance': []},
  'kernelspec': {'name': 'python3', 'display_name': 'Python 3'},
  'language_info': {'name': 'python'}},
 'cells': [{'cell_type': 'markdown',
   'source': ['Task 3'],
   'metadata': {'id': 'rMGwRaw9us9f'}},
  {'cell_type': 'code',
   'execution_count': 1,
   'metadata': {'id': 'qovH03houYEV'},
   'outputs': [],
   'source': ['import pandas as pd\n',
    'from sklearn.model_selection import train_test_split\n',
    'from sklearn.tree import DecisionTreeClassifier\n',
    'from sklearn.metrics import accuracy_score, classification_report, confusion_matrix\n',
    'import matplotlib.pyplot as plt\n',
    'import seaborn as sns\n',
    'from sklearn.tree import export_text\n',
    'from sklearn.tree import export_graphviz\n',
    'import graphviz']},
  {'cell_type': 'code',
   'source': ['data = pd.read_csv("bank.csv")\n', 'data.head()'],
   'metadata': {'colab': {'base_uri': 'https://localhost:8080/',
     'height': 206},
    'id': 'Ck1iDU3Ju30f',
    'outputId': 'd85e2d98-159c-434d-860b-5691a94b240e'},
   'execution_count': 4,
   'outputs': [{'output_type': 'execute_result',
     'data': {'text/plain': ['   age         job  marital  education default  balance housing loan  contact  \\\n',
       '0   59      admin.  married  secondary      no     2343     yes   no  unknown   \n',
       '1   56      admin.  married  secondary      no       45      no   no  unknown   \n',
       '2   41  technician  married  secondary      no     1270     yes   no  unknown   \n',
       '3   55    services  married  secondary      no     2476     yes   no  unknown   \n',
       '4   54      admin.  married   tertiary      no      184      no   no  unknown   \n',
       '\n',
       '   day month  duration  campaign  pdays  previous poutcome deposit  \n',
       '0    5   may      1042         1     -1         0  unknown     yes  \n',
       '1    5   may      1467         1     -1         0  unknown     yes  \n',
       '2    5   may      1389         1     -1         0  unknown     yes  \n',
       '3    5   may       579         1     -1         0  unknown     yes  \n',
       '4    5   may       673         2     -1         0  unknown     yes  '],
      'text/html': ['\n',
       '  <div id="df-695558f6-1da0-478e-bca4-21efddcce38f" class="colab-df-container">\n',
       '    <div>\n',
       '<style scoped>\n',
       '    .dataframe tbody tr th:only-of-type {\n',
       '        vertical-align: middle;\n',
       '    }\n',
       '\n',
       '    .dataframe tbody tr th {\n',
       '        vertical-align: top;\n',
       '    }\n',
       '\n',
       '    .dataframe thead th {\n',
       '        text-align: right;\n',
       '    }\n',
       '</style>\n',
       '<table border="1" class="dataframe">\n',
       '  <thead>\n',
       '    <tr style="text-align: right;">\n',
       '      <th></th>\n',
       '      <th>age</th>\n',
       '      <th>job</th>\n',
       '      <th>marital</th>\n',
       '      <th>education</th>\n',
       '      <th>default</th>\n',
       '      <th>balance</th>\n',
       '      <th>housing</th>\n',
       '      <th>loan</th>\n',
       '      <th>contact</th>\n',
       '      <th>day</th>\n',
       '      <th>month</th>\n',
       '      <th>duration</th>\n',
       '      <th>campaign</th>\n',
       '      <th>pdays</th>\n',
       '      <th>previous</th>\n',
       '      <th>poutcome</th>\n',
       '      <th>deposit</th>\n',
       '    </tr>\n',
       '  </thead>\n',
       '  <tbody>\n',
       '    <tr>\n',
       '      <th>0</th>\n',
       '      <td>59</td>\n',
       '      <td>admin.</td>\n',
       '      <td>married</td>\n',
       '      <td>secondary</td>\n',
       '      <td>no</td>\n',
       '      <td>2343</td>\n',
       '      <td>yes</td>\n',
       '      <td>no</td>\n',
       '      <td>unknown</td>\n',
       '      <td>5</td>\n',
       '      <td>may</td>\n',
       '      <td>1042</td>\n',
       '      <td>1</td>\n',
       '      <td>-1</td>\n',
       '      <td>0</td>\n',
       '      <td>unknown</td>\n',
       '      <td>yes</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>1</th>\n',
       '      <td>56</td>\n',
       '      <td>admin.</td>\n',
       '      <td>married</td>\n',
       '      <td>secondary</td>\n',
       '      <td>no</td>\n',
       '      <td>45</td>\n',
       '      <td>no</td>\n',
       '      <td>no</td>\n',
       '      <td>unknown</td>\n',
       '      <td>5</td>\n',
       '      <td>may</td>\n',
       '      <td>1467</td>\n',
       '      <td>1</td>\n',
       '      <td>-1</td>\n',
       '      <td>0</td>\n',
       '      <td>unknown</td>\n',
       '      <td>yes</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>2</th>\n',
       '      <td>41</td>\n',
       '      <td>technician</td>\n',
       '      <td>married</td>\n',
       '      <td>secondary</td>\n',
       '      <td>no</td>\n',
       '      <td>1270</td>\n',
       '      <td>yes</td>\n',
       '      <td>no</td>\n',
       '      <td>unknown</td>\n',
       '      <td>5</td>\n',
       '      <td>may</td>\n',
       '      <td>1389</td>\n',
       '      <td>1</td>\n',
       '      <td>-1</td>\n',
       '      <td>0</td>\n',
       '      <td>unknown</td>\n',
       '      <td>yes</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>3</th>\n',
       '      <td>55</td>\n',
       '      <td>services</td>\n',
       '      <td>married</td>\n',
       '      <td>secondary</td>\n',
       '      <td>no</td>\n',
       '      <td>2476</td>\n',
       '      <td>yes</td>\n',
       '      <td>no</td>\n',
       '      <td>unknown</td>\n',
       '      <td>5</td>\n',
       '      <td>may</td>\n',
       '      <td>579</td>\n',
       '      <td>1</td>\n',
       '      <td>-1</td>\n',
       '      <td>0</td>\n',
       '      <td>unknown</td>\n',
       '      <td>yes</td>\n',
       '    </tr>\n',
       '    <tr>\n',
       '      <th>4</th>\n',
       '      <td>54</td>\n',
       '      <td>admin.</td>\n',
       '      <td>married</td>\n',
       '      <td>tertiary</td>\n',
       '      <td>no</td>\n',
       '      <td>184</td>\n',
       '      <td>no</td>\n',
       '      <td>no</td>\n',
       '      <td>unknown</td>\n',
       '      <td>5</td>\n',
       '      <td>may</td>\n',
       '      <td>673</td>\n',
       '      <td>2</td>\n',
       '      <td>-1</td>\n',
       '      <td>0</td>\n',
       '      <td>unknown</td>\n',
       '      <td>yes</td>\n',
       '    </tr>\n',
       '  </tbody>\n',
       '</table>\n',
       '</div>\n',
       '    <div class="colab-df-buttons">\n',
       '\n',
       '  <div class="colab-df-container">\n',
       '    <button class="colab-df-convert" onclick="convertToInteractive(\'df-695558f6-1da0-478e-bca4-21efddcce38f\')"\n',
       '            title="Convert this dataframe to an interactive table."\n',
       '            style="display:none;">\n',
       '\n',
       '  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960">\n',
       '    <path d="M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z"/>\n',
       '  </svg>\n',
       '    </button>\n',
       '\n',
       '  <style>\n',
       '    .colab-df-container {\n',
       '      display:flex;\n',
       '      gap: 12px;\n',
       '    }\n',
       '\n',
       '    .colab-df-convert {\n',
       '      background-color: #E8F0FE;\n',
       '      border: none;\n',
       '      border-radius: 50%;\n',
       '      cursor: pointer;\n',
       '      display: none;\n',
       '      fill: #1967D2;\n',
       '      height: 32px;\n',
       '      padding: 0 0 0 0;\n',
       '      width: 32px;\n',
       '    }\n',
       '\n',
       '    .colab-df-convert:hover {\n',
       '      background-color: #E2EBFA;\n',
       '      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n',
       '      fill: #174EA6;\n',
       '    }\n',
       '\n',
       '    .colab-df-buttons div {\n',
       '      margin-bottom: 4px;\n',
       '    }\n',
       '\n',
       '    [theme=dark] .colab-df-convert {\n',
       '      background-color: #3B4455;\n',
       '      fill: #D2E3FC;\n',
       '    }\n',
       '\n',
       '    [theme=dark] .colab-df-convert:hover {\n',
       '      background-color: #434B5C;\n',
       '      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n',
       '      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n',
       '      fill: #FFFFFF;\n',
       '    }\n',
       '  </style>\n',
       '\n',
       '    <script>\n',
       '      const buttonEl =\n',
       "        document.querySelector('#df-695558f6-1da0-478e-bca4-21efddcce38f button.colab-df-convert');\n",
       '      buttonEl.style.display =\n',
       "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
       '\n',
       '      async function convertToInteractive(key) {\n',
       "        const element = document.querySelector('#df-695558f6-1da0-478e-bca4-21efddcce38f');\n",
       '        const dataTable =\n',
       "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
       '                                                    [key], {});\n',
       '        if (!dataTable) return;\n',
       '\n',
       "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
       '          \'<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>\'\n',
       "          + ' to learn more about interactive tables.';\n",
       "        element.innerHTML = '';\n",
       "        dataTable['output_type'] = 'display_data';\n",
       '        await google.colab.output.renderOutput(dataTable, element);\n',
       "        const docLink = document.createElement('div');\n",
       '        docLink.innerHTML = docLinkHtml;\n',
       '        element.appendChild(docLink);\n',
       '      }\n',
       '    </script>\n',
       '  </div>\n',
       '\n',
       '\n',
       '<div id="df-726853c4-8a5d-4a27-9ea8-b830b4144b95">\n',
       '  <button class="colab-df-quickchart" onclick="quickchart(\'df-726853c4-8a5d-4a27-9ea8-b830b4144b95\')"\n',
       '            title="Suggest charts"\n',
       '            style="display:none;">\n',
       '\n',
       '<svg xmlns="http://www.w3.org/2000/svg" height="24px"viewBox="0 0 24 24"\n',
       '     width="24px">\n',
       '    <g>\n',
       '        <path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z"/>\n',
       '    </g>\n',
       '</svg>\n',
       '  </button>\n',
       '\n',
       '<style>\n',
       '  .colab-df-quickchart {\n',
       '      --bg-color: #E8F0FE;\n',
       '      --fill-color: #1967D2;\n',
       '      --hover-bg-color: #E2EBFA;\n',
       '      --hover-fill-color: #174EA6;\n',
       '      --disabled-fill-color: #AAA;\n',
       '      --disabled-bg-color: #DDD;\n',
       '  }\n',
       '\n',
       '  [theme=dark] .colab-df-quickchart {\n',
       '      --bg-color: #3B4455;\n',
       '      --fill-color: #D2E3FC;\n',
       '      --hover-bg-color: #434B5C;\n',
       '      --hover-fill-color: #FFFFFF;\n',
       '      --disabled-bg-color: #3B4455;\n',
       '      --disabled-fill-color: #666;\n',
       '  }\n',
       '\n',
       '  .colab-df-quickchart {\n',
       '    background-color: var(--bg-color);\n',
       '    border: none;\n',
       '    border-radius: 50%;\n',
       '    cursor: pointer;\n',
       '    display: none;\n',
       '    fill: var(--fill-color);\n',
       '    height: 32px;\n',
       '    padding: 0;\n',
       '    width: 32px;\n',
       '  }\n',
       '\n',
       '  .colab-df-quickchart:hover {\n',
       '    background-color: var(--hover-bg-color);\n',
       '    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\n',
       '    fill: var(--button-hover-fill-color);\n',
       '  }\n',
       '\n',
       '  .colab-df-quickchart-complete:disabled,\n',
       '  .colab-df-quickchart-complete:disabled:hover {\n',
       '    background-color: var(--disabled-bg-color);\n',
       '    fill: var(--disabled-fill-color);\n',
       '    box-shadow: none;\n',
       '  }\n',
       '\n',
       '  .colab-df-spinner {\n',
       '    border: 2px solid var(--fill-color);\n',
       '    border-color: transparent;\n',
       '    border-bottom-color: var(--fill-color);\n',
       '    animation:\n',
       '      spin 1s steps(1) infinite;\n',
       '  }\n',
       '\n',
       '  @keyframes spin {\n',
       '    0% {\n',
       '      border-color: transparent;\n',
       '      border-bottom-color: var(--fill-color);\n',
       '      border-left-color: var(--fill-color);\n',
       '    }\n',
       '    20% {\n',
       '      border-color: transparent;\n',
       '      border-left-color: var(--fill-color);\n',
       '      border-top-color: var(--fill-color);\n',
       '    }\n',
       '    30% {\n',
       '      border-color: transparent;\n',
       '      border-left-color: var(--fill-color);\n',
       '      border-top-color: var(--fill-color);\n',
       '      border-right-color: var(--fill-color);\n',
       '    }\n',
       '    40% {\n',
       '      border-color: transparent;\n',
       '      border-right-color: var(--fill-color);\n',
       '      border-top-color: var(--fill-color);\n',
       '    }\n',
       '    60% {\n',
       '      border-color: transparent;\n',
       '      border-right-color: var(--fill-color);\n',
       '    }\n',
       '    80% {\n',
       '      border-color: transparent;\n',
       '      border-right-color: var(--fill-color);\n',
       '      border-bottom-color: var(--fill-color);\n',
       '    }\n',
       '    90% {\n',
       '      border-color: transparent;\n',
       '      border-bottom-color: var(--fill-color);\n',
       '    }\n',
       '  }\n',
       '</style>\n',
       '\n',
       '  <script>\n',
       '    async function quickchart(key) {\n',
       '      const quickchartButtonEl =\n',
       "        document.querySelector('#' + key + ' button');\n",
       '      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\n',
       "      quickchartButtonEl.classList.add('colab-df-spinner');\n",
       '      try {\n',
       '        const charts = await google.colab.kernel.invokeFunction(\n',
       "            'suggestCharts', [key], {});\n",
       '      } catch (error) {\n',
       "        console.error('Error during call to suggestCharts:', error);\n",
       '      }\n',
       "      quickchartButtonEl.classList.remove('colab-df-spinner');\n",
       "      quickchartButtonEl.classList.add('colab-df-quickchart-complete');\n",
       '    }\n',
       '    (() => {\n',
       '      let quickchartButtonEl =\n',
       "        document.querySelector('#df-726853c4-8a5d-4a27-9ea8-b830b4144b95 button');\n",
       '      quickchartButtonEl.style.display =\n',
       "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
       '    })();\n',
       '  </script>\n',
       '</div>\n',
       '\n',
       '    </div>\n',
       '  </div>\n'],
      'application/vnd.google.colaboratory.intrinsic+json': {'type': 'dataframe',
       'variable_name': 'data',